//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sat.CreditosFiscales.Impresion.LogicaNegocio.ServicioImpresion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioImpresion.IServicioImpresion")]
    public interface IServicioImpresion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioImpresion/ObtenerPDF", ReplyAction="http://tempuri.org/IServicioImpresion/ObtenerPDFResponse")]
        byte[] ObtenerPDF(string strXmlDatos, int IdDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioImpresion/ObtenerPNG", ReplyAction="http://tempuri.org/IServicioImpresion/ObtenerPNGResponse")]
        byte[] ObtenerPNG(string strXmlDatos, int IdDocumento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioImpresionChannel : Sat.CreditosFiscales.Impresion.LogicaNegocio.ServicioImpresion.IServicioImpresion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioImpresionClient : System.ServiceModel.ClientBase<Sat.CreditosFiscales.Impresion.LogicaNegocio.ServicioImpresion.IServicioImpresion>, Sat.CreditosFiscales.Impresion.LogicaNegocio.ServicioImpresion.IServicioImpresion {
        
        public ServicioImpresionClient() {
        }
        
        public ServicioImpresionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioImpresionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioImpresionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioImpresionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] ObtenerPDF(string strXmlDatos, int IdDocumento) {
            return base.Channel.ObtenerPDF(strXmlDatos, IdDocumento);
        }
        
        public byte[] ObtenerPNG(string strXmlDatos, int IdDocumento) {
            return base.Channel.ObtenerPNG(strXmlDatos, IdDocumento);
        }
    }
}
