//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMotor.ReglasXsltWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatReglas", Namespace="http://schemas.datacontract.org/2004/07/Sat.CreditosFiscales.Comunes.Entidades.Ca" +
        "talogos")]
    [System.SerializableAttribute()]
    public partial class CatReglas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReglasXsltWCF.IServicioReglasXslt")]
    public interface IServicioReglasXslt {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReglasXslt/ObtieneReglasXslt", ReplyAction="http://tempuri.org/IServicioReglasXslt/ObtieneReglasXsltResponse")]
        TestMotor.ReglasXsltWCF.CatReglas[] ObtieneReglasXslt(string IdRegla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReglasXslt/ObtieneReglasXslt", ReplyAction="http://tempuri.org/IServicioReglasXslt/ObtieneReglasXsltResponse")]
        System.Threading.Tasks.Task<TestMotor.ReglasXsltWCF.CatReglas[]> ObtieneReglasXsltAsync(string IdRegla);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioReglasXsltChannel : TestMotor.ReglasXsltWCF.IServicioReglasXslt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioReglasXsltClient : System.ServiceModel.ClientBase<TestMotor.ReglasXsltWCF.IServicioReglasXslt>, TestMotor.ReglasXsltWCF.IServicioReglasXslt {
        
        public ServicioReglasXsltClient() {
        }
        
        public ServicioReglasXsltClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioReglasXsltClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReglasXsltClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReglasXsltClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestMotor.ReglasXsltWCF.CatReglas[] ObtieneReglasXslt(string IdRegla) {
            return base.Channel.ObtieneReglasXslt(IdRegla);
        }
        
        public System.Threading.Tasks.Task<TestMotor.ReglasXsltWCF.CatReglas[]> ObtieneReglasXsltAsync(string IdRegla) {
            return base.Channel.ObtieneReglasXsltAsync(IdRegla);
        }
    }
}
