//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SolicitudCreditosFiscales {
    
    private SolicitudCreditosFiscalesEncabezado encabezadoField;
    
    private SolicitudCreditosFiscalesMensaje mensajeField;
    
    /// <remarks/>
    public SolicitudCreditosFiscalesEncabezado Encabezado {
        get {
            return this.encabezadoField;
        }
        set {
            this.encabezadoField = value;
        }
    }
    
    /// <remarks/>
    public SolicitudCreditosFiscalesMensaje Mensaje {
        get {
            return this.mensajeField;
        }
        set {
            this.mensajeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SolicitudCreditosFiscalesEncabezado {
    
    private int tipoDocumentoField;
    
    private string descripcionTipoDocumentoField;
    
    private int aplicacionField;
    
    /// <remarks/>
    public int TipoDocumento {
        get {
            return this.tipoDocumentoField;
        }
        set {
            this.tipoDocumentoField = value;
        }
    }
    
    /// <remarks/>
    public string DescripcionTipoDocumento {
        get {
            return this.descripcionTipoDocumentoField;
        }
        set {
            this.descripcionTipoDocumentoField = value;
        }
    }
    
    /// <remarks/>
    public int Aplicacion {
        get {
            return this.aplicacionField;
        }
        set {
            this.aplicacionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SolicitudCreditosFiscalesMensaje {
    
    private SolicitudCreditosFiscalesMensajeDatosGenerales datosGeneralesField;
    
    private SolicitudCreditosFiscalesMensajeResolucionDeterminante[] resolucionesDeterminanteField;
    
    /// <remarks/>
    public SolicitudCreditosFiscalesMensajeDatosGenerales DatosGenerales {
        get {
            return this.datosGeneralesField;
        }
        set {
            this.datosGeneralesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ResolucionDeterminante", IsNullable=false)]
    public SolicitudCreditosFiscalesMensajeResolucionDeterminante[] ResolucionesDeterminante {
        get {
            return this.resolucionesDeterminanteField;
        }
        set {
            this.resolucionesDeterminanteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SolicitudCreditosFiscalesMensajeDatosGenerales {
    
    private string rFCField;
    
    private string nombreField;
    
    private string apellidoPaternoField;
    
    private string apellidoMaternoField;
    
    private string razonSocialField;
    
    private int aLRField;
    
    private string bOIDField;
    
    private SolicitudCreditosFiscalesMensajeDatosGeneralesLineaCaptura lineaCapturaField;
    
    /// <remarks/>
    public string RFC {
        get {
            return this.rFCField;
        }
        set {
            this.rFCField = value;
        }
    }
    
    /// <remarks/>
    public string Nombre {
        get {
            return this.nombreField;
        }
        set {
            this.nombreField = value;
        }
    }
    
    /// <remarks/>
    public string ApellidoPaterno {
        get {
            return this.apellidoPaternoField;
        }
        set {
            this.apellidoPaternoField = value;
        }
    }
    
    /// <remarks/>
    public string ApellidoMaterno {
        get {
            return this.apellidoMaternoField;
        }
        set {
            this.apellidoMaternoField = value;
        }
    }
    
    /// <remarks/>
    public string RazonSocial {
        get {
            return this.razonSocialField;
        }
        set {
            this.razonSocialField = value;
        }
    }
    
    /// <remarks/>
    public int ALR {
        get {
            return this.aLRField;
        }
        set {
            this.aLRField = value;
        }
    }
    
    /// <remarks/>
    public string BOID {
        get {
            return this.bOIDField;
        }
        set {
            this.bOIDField = value;
        }
    }
    
    /// <remarks/>
    public SolicitudCreditosFiscalesMensajeDatosGeneralesLineaCaptura LineaCaptura {
        get {
            return this.lineaCapturaField;
        }
        set {
            this.lineaCapturaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SolicitudCreditosFiscalesMensajeDatosGeneralesLineaCaptura {
    
    private long importeField;
    
    private string fechaVigenciaField;
    
    private int pagoObligadoInternetField;
    
    /// <remarks/>
    public long Importe {
        get {
            return this.importeField;
        }
        set {
            this.importeField = value;
        }
    }
    
    /// <remarks/>
    public string FechaVigencia {
        get {
            return this.fechaVigenciaField;
        }
        set {
            this.fechaVigenciaField = value;
        }
    }
    
    /// <remarks/>
    public int PagoObligadoInternet {
        get {
            return this.pagoObligadoInternetField;
        }
        set {
            this.pagoObligadoInternetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SolicitudCreditosFiscalesMensajeResolucionDeterminante {
    
    private string numeroResolucionField;
    
    private string fechaField;
    
    private int autoridadIdField;
    
    private int aLRField;
    
    private string rFCField;
    
    private SolicitudCreditosFiscalesMensajeResolucionDeterminanteMarca[] marcasField;
    
    private SolicitudCreditosFiscalesMensajeResolucionDeterminanteConcepto[] conceptosField;
    
    /// <remarks/>
    public string NumeroResolucion {
        get {
            return this.numeroResolucionField;
        }
        set {
            this.numeroResolucionField = value;
        }
    }
    
    /// <remarks/>
    public string Fecha {
        get {
            return this.fechaField;
        }
        set {
            this.fechaField = value;
        }
    }
    
    /// <remarks/>
    public int AutoridadId {
        get {
            return this.autoridadIdField;
        }
        set {
            this.autoridadIdField = value;
        }
    }
    
    /// <remarks/>
    public int ALR {
        get {
            return this.aLRField;
        }
        set {
            this.aLRField = value;
        }
    }
    
    /// <remarks/>
    public string RFC {
        get {
            return this.rFCField;
        }
        set {
            this.rFCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Marca", IsNullable=false)]
    public SolicitudCreditosFiscalesMensajeResolucionDeterminanteMarca[] Marcas {
        get {
            return this.marcasField;
        }
        set {
            this.marcasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Concepto", IsNullable=false)]
    public SolicitudCreditosFiscalesMensajeResolucionDeterminanteConcepto[] Conceptos {
        get {
            return this.conceptosField;
        }
        set {
            this.conceptosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SolicitudCreditosFiscalesMensajeResolucionDeterminanteMarca {
    
    private string tipoMarcaField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoMarca {
        get {
            return this.tipoMarcaField;
        }
        set {
            this.tipoMarcaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SolicitudCreditosFiscalesMensajeResolucionDeterminanteConcepto {
    
    private string claveField;
    
    private int ejercicioField;
    
    private bool ejercicioFieldSpecified;
    
    private int periodicidadIdField;
    
    private int periodoIdField;
    
    private string motivoIdField;
    
    private string fechaCausacionField;
    
    private int creditoSirField;
    
    private int credicoARCAField;
    
    private bool credicoARCAFieldSpecified;
    
    private decimal importeHistoricoField;
    
    private decimal importeParteActualizadaField;
    
    private decimal importePagarField;
    
    private string fechaNotificacionField;
    
    private bool liquidarField;
    
    private SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoMarca[] marcasField;
    
    private SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoDescuento[] descuentosField;
    
    private SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoHijo[] hijosField;
    
    /// <remarks/>
    public string Clave {
        get {
            return this.claveField;
        }
        set {
            this.claveField = value;
        }
    }
    
    /// <remarks/>
    public int Ejercicio {
        get {
            return this.ejercicioField;
        }
        set {
            this.ejercicioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EjercicioSpecified {
        get {
            return this.ejercicioFieldSpecified;
        }
        set {
            this.ejercicioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int PeriodicidadId {
        get {
            return this.periodicidadIdField;
        }
        set {
            this.periodicidadIdField = value;
        }
    }
    
    /// <remarks/>
    public int PeriodoId {
        get {
            return this.periodoIdField;
        }
        set {
            this.periodoIdField = value;
        }
    }
    
    /// <remarks/>
    public string MotivoId {
        get {
            return this.motivoIdField;
        }
        set {
            this.motivoIdField = value;
        }
    }
    
    /// <remarks/>
    public string FechaCausacion {
        get {
            return this.fechaCausacionField;
        }
        set {
            this.fechaCausacionField = value;
        }
    }
    
    /// <remarks/>
    public int CreditoSir {
        get {
            return this.creditoSirField;
        }
        set {
            this.creditoSirField = value;
        }
    }
    
    /// <remarks/>
    public int CredicoARCA {
        get {
            return this.credicoARCAField;
        }
        set {
            this.credicoARCAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CredicoARCASpecified {
        get {
            return this.credicoARCAFieldSpecified;
        }
        set {
            this.credicoARCAFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal ImporteHistorico {
        get {
            return this.importeHistoricoField;
        }
        set {
            this.importeHistoricoField = value;
        }
    }
    
    /// <remarks/>
    public decimal ImporteParteActualizada {
        get {
            return this.importeParteActualizadaField;
        }
        set {
            this.importeParteActualizadaField = value;
        }
    }
    
    /// <remarks/>
    public decimal ImportePagar {
        get {
            return this.importePagarField;
        }
        set {
            this.importePagarField = value;
        }
    }
    
    /// <remarks/>
    public string FechaNotificacion {
        get {
            return this.fechaNotificacionField;
        }
        set {
            this.fechaNotificacionField = value;
        }
    }
    
    /// <remarks/>
    public bool Liquidar {
        get {
            return this.liquidarField;
        }
        set {
            this.liquidarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Marca", IsNullable=false)]
    public SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoMarca[] Marcas {
        get {
            return this.marcasField;
        }
        set {
            this.marcasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Descuento", IsNullable=false)]
    public SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoDescuento[] Descuentos {
        get {
            return this.descuentosField;
        }
        set {
            this.descuentosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Hijo", IsNullable=false)]
    public SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoHijo[] Hijos {
        get {
            return this.hijosField;
        }
        set {
            this.hijosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoMarca {
    
    private string tipoMarcaField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoMarca {
        get {
            return this.tipoMarcaField;
        }
        set {
            this.tipoMarcaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoDescuento {
    
    private int idDescuentoField;
    
    private decimal importeDescuentoField;
    
    /// <remarks/>
    public int IdDescuento {
        get {
            return this.idDescuentoField;
        }
        set {
            this.idDescuentoField = value;
        }
    }
    
    /// <remarks/>
    public decimal ImporteDescuento {
        get {
            return this.importeDescuentoField;
        }
        set {
            this.importeDescuentoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoHijo {
    
    private string claveField;
    
    private string motivoIdField;
    
    private string fechaCausacionField;
    
    private int creditoSirField;
    
    private decimal importeHistoricoField;
    
    private decimal importeParteActualizadaField;
    
    private decimal importePagarField;
    
    private string fechaNotificacionField;
    
    private int ejercicioField;
    
    private bool ejercicioFieldSpecified;
    
    private int periodicidadIdField;
    
    private int periodoIdField;
    
    private bool liquidarField;
    
    private SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoHijoMarca[] marcasField;
    
    private SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoHijoDescuento[] descuentosField;
    
    /// <remarks/>
    public string Clave {
        get {
            return this.claveField;
        }
        set {
            this.claveField = value;
        }
    }
    
    /// <remarks/>
    public string MotivoId {
        get {
            return this.motivoIdField;
        }
        set {
            this.motivoIdField = value;
        }
    }
    
    /// <remarks/>
    public string FechaCausacion {
        get {
            return this.fechaCausacionField;
        }
        set {
            this.fechaCausacionField = value;
        }
    }
    
    /// <remarks/>
    public int CreditoSir {
        get {
            return this.creditoSirField;
        }
        set {
            this.creditoSirField = value;
        }
    }
    
    /// <remarks/>
    public decimal ImporteHistorico {
        get {
            return this.importeHistoricoField;
        }
        set {
            this.importeHistoricoField = value;
        }
    }
    
    /// <remarks/>
    public decimal ImporteParteActualizada {
        get {
            return this.importeParteActualizadaField;
        }
        set {
            this.importeParteActualizadaField = value;
        }
    }
    
    /// <remarks/>
    public decimal ImportePagar {
        get {
            return this.importePagarField;
        }
        set {
            this.importePagarField = value;
        }
    }
    
    /// <remarks/>
    public string FechaNotificacion {
        get {
            return this.fechaNotificacionField;
        }
        set {
            this.fechaNotificacionField = value;
        }
    }
    
    /// <remarks/>
    public int Ejercicio {
        get {
            return this.ejercicioField;
        }
        set {
            this.ejercicioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EjercicioSpecified {
        get {
            return this.ejercicioFieldSpecified;
        }
        set {
            this.ejercicioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int PeriodicidadId {
        get {
            return this.periodicidadIdField;
        }
        set {
            this.periodicidadIdField = value;
        }
    }
    
    /// <remarks/>
    public int PeriodoId {
        get {
            return this.periodoIdField;
        }
        set {
            this.periodoIdField = value;
        }
    }
    
    /// <remarks/>
    public bool Liquidar {
        get {
            return this.liquidarField;
        }
        set {
            this.liquidarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Marca", IsNullable=false)]
    public SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoHijoMarca[] Marcas {
        get {
            return this.marcasField;
        }
        set {
            this.marcasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Descuento", IsNullable=false)]
    public SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoHijoDescuento[] Descuentos {
        get {
            return this.descuentosField;
        }
        set {
            this.descuentosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoHijoMarca {
    
    private string tipoMarcaField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoMarca {
        get {
            return this.tipoMarcaField;
        }
        set {
            this.tipoMarcaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SolicitudCreditosFiscalesMensajeResolucionDeterminanteConceptoHijoDescuento {
    
    private int idDescuentoField;
    
    private decimal importeDescuentoField;
    
    /// <remarks/>
    public int IdDescuento {
        get {
            return this.idDescuentoField;
        }
        set {
            this.idDescuentoField = value;
        }
    }
    
    /// <remarks/>
    public decimal ImporteDescuento {
        get {
            return this.importeDescuentoField;
        }
        set {
            this.importeDescuentoField = value;
        }
    }
}
