//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.CreditosFiscales.Motor.Pruebas.RecepcionLC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Sat.Scade.Sispr", ConfigurationName="RecepcionLC.IRecepcion")]
    public interface IRecepcion {
        
        [System.ServiceModel.OperationContractAttribute(Action="Sat.Scade.Sispr/IRecepcion/GenerarLineaCaptura", ReplyAction="Sat.Scade.Sispr/IRecepcion/GenerarLineaCapturaResponse")]
        SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.RespuestaGeneracionLC GenerarLineaCaptura(SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.SolicitudGeneracionLC solicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecepcionChannel : SAT.CreditosFiscales.Motor.Pruebas.RecepcionLC.IRecepcion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecepcionClient : System.ServiceModel.ClientBase<SAT.CreditosFiscales.Motor.Pruebas.RecepcionLC.IRecepcion>, SAT.CreditosFiscales.Motor.Pruebas.RecepcionLC.IRecepcion {
        
        public RecepcionClient() {
        }
        
        public RecepcionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecepcionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.RespuestaGeneracionLC GenerarLineaCaptura(SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.SolicitudGeneracionLC solicitud) {
            return base.Channel.GenerarLineaCaptura(solicitud);
        }
    }
}
