//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class RespuestaLineasCapturaExistentes
{

	private RespuestaLineasCapturaExistentesDatosLinea[] lineasCapturaField;

	private string[] listaErroresField;

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	[System.Xml.Serialization.XmlArrayItemAttribute("DatosLinea", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
	public RespuestaLineasCapturaExistentesDatosLinea[] LineasCaptura
	{
		get
		{
			return this.lineasCapturaField;
		}
		set
		{
			this.lineasCapturaField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	[System.Xml.Serialization.XmlArrayItemAttribute("Error", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
	public string[] ListaErrores
	{
		get
		{
			return this.listaErroresField;
		}
		set
		{
			this.listaErroresField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RespuestaLineasCapturaExistentesDatosLinea
{

	private string folioField;

	private string lineaCapturaField;

	private string fechaGeneracionField;

	private string fechaVigeneciaField;

	private string importeField;

	private string numeroResolucionField;

	private string fechaDocumentoField;

	private string aLRField;

	private string rFCField;

	private string autoridadField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Folio
	{
		get
		{
			return this.folioField;
		}
		set
		{
			this.folioField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string LineaCaptura
	{
		get
		{
			return this.lineaCapturaField;
		}
		set
		{
			this.lineaCapturaField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string FechaGeneracion
	{
		get
		{
			return this.fechaGeneracionField;
		}
		set
		{
			this.fechaGeneracionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string FechaVigenecia
	{
		get
		{
			return this.fechaVigeneciaField;
		}
		set
		{
			this.fechaVigeneciaField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Importe
	{
		get
		{
			return this.importeField;
		}
		set
		{
			this.importeField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string NumeroResolucion
	{
		get
		{
			return this.numeroResolucionField;
		}
		set
		{
			this.numeroResolucionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string FechaDocumento
	{
		get
		{
			return this.fechaDocumentoField;
		}
		set
		{
			this.fechaDocumentoField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string ALR
	{
		get
		{
			return this.aLRField;
		}
		set
		{
			this.aLRField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string RFC
	{
		get
		{
			return this.rFCField;
		}
		set
		{
			this.rFCField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Autoridad
	{
		get
		{
			return this.autoridadField;
		}
		set
		{
			this.autoridadField = value;
		}
	}
}
