//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.CreditosFiscales.Motor.Negocio.ServicioImpresion {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumTemplate", Namespace="http://schemas.datacontract.org/2004/07/Sat.CreditosFiscales.Impresion.Entidades")]
    public enum EnumTemplate : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormatoParaPago = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormatoConfirmacionDeTransaccionesVirtuales = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormatoConfirmacionDeMovimientosContables = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormatoConfirmacionDeRectificacionesContables = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioImpresion.IServicioGeneraFormatoImpresion")]
    public interface IServicioGeneraFormatoImpresion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneraFormatoImpresion/GeneraArchivo", ReplyAction="http://tempuri.org/IServicioGeneraFormatoImpresion/GeneraArchivoResponse")]
        byte[] GeneraArchivo(SAT.CreditosFiscales.Motor.Negocio.ServicioImpresion.EnumTemplate template, string[] listaDeFolios);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioGeneraFormatoImpresionChannel : SAT.CreditosFiscales.Motor.Negocio.ServicioImpresion.IServicioGeneraFormatoImpresion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGeneraFormatoImpresionClient : System.ServiceModel.ClientBase<SAT.CreditosFiscales.Motor.Negocio.ServicioImpresion.IServicioGeneraFormatoImpresion>, SAT.CreditosFiscales.Motor.Negocio.ServicioImpresion.IServicioGeneraFormatoImpresion {
        
        public ServicioGeneraFormatoImpresionClient() {
        }
        
        public ServicioGeneraFormatoImpresionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGeneraFormatoImpresionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGeneraFormatoImpresionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGeneraFormatoImpresionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GeneraArchivo(SAT.CreditosFiscales.Motor.Negocio.ServicioImpresion.EnumTemplate template, string[] listaDeFolios) {
            return base.Channel.GeneraArchivo(template, listaDeFolios);
        }
    }
}
