//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sat.Scade.Net.IDE.Presentacion.Web.ServiceRecepcion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecEntrada", Namespace="http://schemas.datacontract.org/2004/07/RecepcionIDEWEB.Negocio.Contratos")]
    [System.SerializableAttribute()]
    public partial class RecEntrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoFisicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsAnualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsNormalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEntidadReceptoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMedioRecepcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RfcAutenticacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RfcContribuyenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TamañoArchivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivoFisico {
            get {
                return this.ArchivoFisicoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoFisicoField, value) != true)) {
                    this.ArchivoFisicoField = value;
                    this.RaisePropertyChanged("ArchivoFisico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionIP {
            get {
                return this.DireccionIPField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionIPField, value) != true)) {
                    this.DireccionIPField = value;
                    this.RaisePropertyChanged("DireccionIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsAnual {
            get {
                return this.EsAnualField;
            }
            set {
                if ((this.EsAnualField.Equals(value) != true)) {
                    this.EsAnualField = value;
                    this.RaisePropertyChanged("EsAnual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsNormal {
            get {
                return this.EsNormalField;
            }
            set {
                if ((this.EsNormalField.Equals(value) != true)) {
                    this.EsNormalField = value;
                    this.RaisePropertyChanged("EsNormal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formato {
            get {
                return this.FormatoField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatoField, value) != true)) {
                    this.FormatoField = value;
                    this.RaisePropertyChanged("Formato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEntidadReceptora {
            get {
                return this.IdEntidadReceptoraField;
            }
            set {
                if ((this.IdEntidadReceptoraField.Equals(value) != true)) {
                    this.IdEntidadReceptoraField = value;
                    this.RaisePropertyChanged("IdEntidadReceptora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMedioRecepcion {
            get {
                return this.IdMedioRecepcionField;
            }
            set {
                if ((this.IdMedioRecepcionField.Equals(value) != true)) {
                    this.IdMedioRecepcionField = value;
                    this.RaisePropertyChanged("IdMedioRecepcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Materia {
            get {
                return this.MateriaField;
            }
            set {
                if ((this.MateriaField.Equals(value) != true)) {
                    this.MateriaField = value;
                    this.RaisePropertyChanged("Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreArchivo {
            get {
                return this.NombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArchivoField, value) != true)) {
                    this.NombreArchivoField = value;
                    this.RaisePropertyChanged("NombreArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RfcAutenticacion {
            get {
                return this.RfcAutenticacionField;
            }
            set {
                if ((object.ReferenceEquals(this.RfcAutenticacionField, value) != true)) {
                    this.RfcAutenticacionField = value;
                    this.RaisePropertyChanged("RfcAutenticacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RfcContribuyente {
            get {
                return this.RfcContribuyenteField;
            }
            set {
                if ((object.ReferenceEquals(this.RfcContribuyenteField, value) != true)) {
                    this.RfcContribuyenteField = value;
                    this.RaisePropertyChanged("RfcContribuyente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TamañoArchivo {
            get {
                return this.TamañoArchivoField;
            }
            set {
                if ((this.TamañoArchivoField.Equals(value) != true)) {
                    this.TamañoArchivoField = value;
                    this.RaisePropertyChanged("TamañoArchivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecSalida", Namespace="http://schemas.datacontract.org/2004/07/RecepcionIDEWEB.Negocio.Contratos")]
    [System.SerializableAttribute()]
    public partial class RecSalida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RfcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TamanoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((this.FolioField.Equals(value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rfc {
            get {
                return this.RfcField;
            }
            set {
                if ((object.ReferenceEquals(this.RfcField, value) != true)) {
                    this.RfcField = value;
                    this.RaisePropertyChanged("Rfc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tamano {
            get {
                return this.TamanoField;
            }
            set {
                if ((this.TamanoField.Equals(value) != true)) {
                    this.TamanoField = value;
                    this.RaisePropertyChanged("Tamano");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecVerifica", Namespace="http://schemas.datacontract.org/2004/07/RecepcionIDEWEB.Negocio.Contratos")]
    [System.SerializableAttribute()]
    public partial class RecVerifica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExistenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FolioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Existencia {
            get {
                return this.ExistenciaField;
            }
            set {
                if ((this.ExistenciaField.Equals(value) != true)) {
                    this.ExistenciaField = value;
                    this.RaisePropertyChanged("Existencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((this.FolioField.Equals(value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://schemas.datacontract.org/2004/07/RecepcionIDEWEB.Negocio.Contratos")]
    [System.SerializableAttribute()]
    public partial class Mensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoMensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMensaje {
            get {
                return this.IdMensajeField;
            }
            set {
                if ((this.IdMensajeField.Equals(value) != true)) {
                    this.IdMensajeField = value;
                    this.RaisePropertyChanged("IdMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoMensaje {
            get {
                return this.IdTipoMensajeField;
            }
            set {
                if ((this.IdTipoMensajeField.Equals(value) != true)) {
                    this.IdTipoMensajeField = value;
                    this.RaisePropertyChanged("IdTipoMensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRecepcion.IRecepcion")]
    public interface IRecepcion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecepcion/RegistrarArchivo", ReplyAction="http://tempuri.org/IRecepcion/RegistrarArchivoResponse")]
        Sat.Scade.Net.IDE.Presentacion.Web.ServiceRecepcion.RecSalida RegistrarArchivo(Sat.Scade.Net.IDE.Presentacion.Web.ServiceRecepcion.RecEntrada ObjRecep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecepcion/ExisteArchivo", ReplyAction="http://tempuri.org/IRecepcion/ExisteArchivoResponse")]
        Sat.Scade.Net.IDE.Presentacion.Web.ServiceRecepcion.RecVerifica ExisteArchivo(string archivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecepcion/GetMensajes", ReplyAction="http://tempuri.org/IRecepcion/GetMensajesResponse")]
        Sat.Scade.Net.IDE.Presentacion.Web.ServiceRecepcion.Mensaje[] GetMensajes(int idTipoMensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecepcion/SiDesEncripta", ReplyAction="http://tempuri.org/IRecepcion/SiDesEncriptaResponse")]
        long SiDesEncripta(string rutaArch, string archOrig);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecepcionChannel : Sat.Scade.Net.IDE.Presentacion.Web.ServiceRecepcion.IRecepcion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecepcionClient : System.ServiceModel.ClientBase<Sat.Scade.Net.IDE.Presentacion.Web.ServiceRecepcion.IRecepcion>, Sat.Scade.Net.IDE.Presentacion.Web.ServiceRecepcion.IRecepcion {
        
        public RecepcionClient() {
        }
        
        public RecepcionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecepcionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sat.Scade.Net.IDE.Presentacion.Web.ServiceRecepcion.RecSalida RegistrarArchivo(Sat.Scade.Net.IDE.Presentacion.Web.ServiceRecepcion.RecEntrada ObjRecep) {
            return base.Channel.RegistrarArchivo(ObjRecep);
        }
        
        public Sat.Scade.Net.IDE.Presentacion.Web.ServiceRecepcion.RecVerifica ExisteArchivo(string archivo) {
            return base.Channel.ExisteArchivo(archivo);
        }
        
        public Sat.Scade.Net.IDE.Presentacion.Web.ServiceRecepcion.Mensaje[] GetMensajes(int idTipoMensaje) {
            return base.Channel.GetMensajes(idTipoMensaje);
        }
        
        public long SiDesEncripta(string rutaArch, string archOrig) {
            return base.Channel.SiDesEncripta(rutaArch, archOrig);
        }
    }
}
