//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3625.
// 
#pragma warning disable 1591

namespace SAT.DyP.Presentacion.Seguridad.Membresia.wsIDCValidate {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="idcValidationSoap", Namespace="http://tempuri.org/")]
    public partial class idcValidation : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateUserModuleOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPerfilOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDatosFIELOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenNombreRazonSocialOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenDatosUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizaMailOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarFIELOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeerAtributoDirectorioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public idcValidation() {
            this.Url = global::SAT.DyP.Presentacion.Seguridad.Membresia.Properties.Settings.Default.SAT_SCADE_NET_Presentacion_Seguridad_Membresia_wsIDCValidate_idcValidation;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateUserCompletedEventHandler ValidateUserCompleted;
        
        /// <remarks/>
        public event ValidateUserModuleCompletedEventHandler ValidateUserModuleCompleted;
        
        /// <remarks/>
        public event ObtenerPerfilCompletedEventHandler ObtenerPerfilCompleted;
        
        /// <remarks/>
        public event ObtenerDatosFIELCompletedEventHandler ObtenerDatosFIELCompleted;
        
        /// <remarks/>
        public event ObtenNombreRazonSocialCompletedEventHandler ObtenNombreRazonSocialCompleted;
        
        /// <remarks/>
        public event ObtenDatosUsuarioCompletedEventHandler ObtenDatosUsuarioCompleted;
        
        /// <remarks/>
        public event ActualizaMailCompletedEventHandler ActualizaMailCompleted;
        
        /// <remarks/>
        public event VerificarFIELCompletedEventHandler VerificarFIELCompleted;
        
        /// <remarks/>
        public event LeerAtributoDirectorioCompletedEventHandler LeerAtributoDirectorioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidateUser(string _userName, string _password, bool enableCIECFortalecida) {
            object[] results = this.Invoke("ValidateUser", new object[] {
                        _userName,
                        _password,
                        enableCIECFortalecida});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string _userName, string _password, bool enableCIECFortalecida) {
            this.ValidateUserAsync(_userName, _password, enableCIECFortalecida, null);
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string _userName, string _password, bool enableCIECFortalecida, object userState) {
            if ((this.ValidateUserOperationCompleted == null)) {
                this.ValidateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserOperationCompleted);
            }
            this.InvokeAsync("ValidateUser", new object[] {
                        _userName,
                        _password,
                        enableCIECFortalecida}, this.ValidateUserOperationCompleted, userState);
        }
        
        private void OnValidateUserOperationCompleted(object arg) {
            if ((this.ValidateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserCompleted(this, new ValidateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateUserModule", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidateUserModule(string userName, string password, string profile) {
            object[] results = this.Invoke("ValidateUserModule", new object[] {
                        userName,
                        password,
                        profile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserModuleAsync(string userName, string password, string profile) {
            this.ValidateUserModuleAsync(userName, password, profile, null);
        }
        
        /// <remarks/>
        public void ValidateUserModuleAsync(string userName, string password, string profile, object userState) {
            if ((this.ValidateUserModuleOperationCompleted == null)) {
                this.ValidateUserModuleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserModuleOperationCompleted);
            }
            this.InvokeAsync("ValidateUserModule", new object[] {
                        userName,
                        password,
                        profile}, this.ValidateUserModuleOperationCompleted, userState);
        }
        
        private void OnValidateUserModuleOperationCompleted(object arg) {
            if ((this.ValidateUserModuleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserModuleCompleted(this, new ValidateUserModuleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerPerfil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerPerfil(string userName) {
            object[] results = this.Invoke("ObtenerPerfil", new object[] {
                        userName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPerfilAsync(string userName) {
            this.ObtenerPerfilAsync(userName, null);
        }
        
        /// <remarks/>
        public void ObtenerPerfilAsync(string userName, object userState) {
            if ((this.ObtenerPerfilOperationCompleted == null)) {
                this.ObtenerPerfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPerfilOperationCompleted);
            }
            this.InvokeAsync("ObtenerPerfil", new object[] {
                        userName}, this.ObtenerPerfilOperationCompleted, userState);
        }
        
        private void OnObtenerPerfilOperationCompleted(object arg) {
            if ((this.ObtenerPerfilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPerfilCompleted(this, new ObtenerPerfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDatosFIEL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FIELCertificateInfo ObtenerDatosFIEL(string certificateSerialNumber) {
            object[] results = this.Invoke("ObtenerDatosFIEL", new object[] {
                        certificateSerialNumber});
            return ((FIELCertificateInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDatosFIELAsync(string certificateSerialNumber) {
            this.ObtenerDatosFIELAsync(certificateSerialNumber, null);
        }
        
        /// <remarks/>
        public void ObtenerDatosFIELAsync(string certificateSerialNumber, object userState) {
            if ((this.ObtenerDatosFIELOperationCompleted == null)) {
                this.ObtenerDatosFIELOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDatosFIELOperationCompleted);
            }
            this.InvokeAsync("ObtenerDatosFIEL", new object[] {
                        certificateSerialNumber}, this.ObtenerDatosFIELOperationCompleted, userState);
        }
        
        private void OnObtenerDatosFIELOperationCompleted(object arg) {
            if ((this.ObtenerDatosFIELCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDatosFIELCompleted(this, new ObtenerDatosFIELCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenNombreRazonSocial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenNombreRazonSocial(string _rfc) {
            object[] results = this.Invoke("ObtenNombreRazonSocial", new object[] {
                        _rfc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenNombreRazonSocialAsync(string _rfc) {
            this.ObtenNombreRazonSocialAsync(_rfc, null);
        }
        
        /// <remarks/>
        public void ObtenNombreRazonSocialAsync(string _rfc, object userState) {
            if ((this.ObtenNombreRazonSocialOperationCompleted == null)) {
                this.ObtenNombreRazonSocialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenNombreRazonSocialOperationCompleted);
            }
            this.InvokeAsync("ObtenNombreRazonSocial", new object[] {
                        _rfc}, this.ObtenNombreRazonSocialOperationCompleted, userState);
        }
        
        private void OnObtenNombreRazonSocialOperationCompleted(object arg) {
            if ((this.ObtenNombreRazonSocialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenNombreRazonSocialCompleted(this, new ObtenNombreRazonSocialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenDatosUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserResponse ObtenDatosUsuario(string rfc) {
            object[] results = this.Invoke("ObtenDatosUsuario", new object[] {
                        rfc});
            return ((UserResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenDatosUsuarioAsync(string rfc) {
            this.ObtenDatosUsuarioAsync(rfc, null);
        }
        
        /// <remarks/>
        public void ObtenDatosUsuarioAsync(string rfc, object userState) {
            if ((this.ObtenDatosUsuarioOperationCompleted == null)) {
                this.ObtenDatosUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenDatosUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenDatosUsuario", new object[] {
                        rfc}, this.ObtenDatosUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenDatosUsuarioOperationCompleted(object arg) {
            if ((this.ObtenDatosUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenDatosUsuarioCompleted(this, new ObtenDatosUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizaMail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizaMail(string rfc, string email) {
            object[] results = this.Invoke("ActualizaMail", new object[] {
                        rfc,
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizaMailAsync(string rfc, string email) {
            this.ActualizaMailAsync(rfc, email, null);
        }
        
        /// <remarks/>
        public void ActualizaMailAsync(string rfc, string email, object userState) {
            if ((this.ActualizaMailOperationCompleted == null)) {
                this.ActualizaMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizaMailOperationCompleted);
            }
            this.InvokeAsync("ActualizaMail", new object[] {
                        rfc,
                        email}, this.ActualizaMailOperationCompleted, userState);
        }
        
        private void OnActualizaMailOperationCompleted(object arg) {
            if ((this.ActualizaMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizaMailCompleted(this, new ActualizaMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificarFIEL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerificarFIEL(string rfc) {
            object[] results = this.Invoke("VerificarFIEL", new object[] {
                        rfc});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarFIELAsync(string rfc) {
            this.VerificarFIELAsync(rfc, null);
        }
        
        /// <remarks/>
        public void VerificarFIELAsync(string rfc, object userState) {
            if ((this.VerificarFIELOperationCompleted == null)) {
                this.VerificarFIELOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarFIELOperationCompleted);
            }
            this.InvokeAsync("VerificarFIEL", new object[] {
                        rfc}, this.VerificarFIELOperationCompleted, userState);
        }
        
        private void OnVerificarFIELOperationCompleted(object arg) {
            if ((this.VerificarFIELCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarFIELCompleted(this, new VerificarFIELCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LeerAtributoDirectorio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LeerAtributoDirectorio(string userName, string attributeName) {
            object[] results = this.Invoke("LeerAtributoDirectorio", new object[] {
                        userName,
                        attributeName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LeerAtributoDirectorioAsync(string userName, string attributeName) {
            this.LeerAtributoDirectorioAsync(userName, attributeName, null);
        }
        
        /// <remarks/>
        public void LeerAtributoDirectorioAsync(string userName, string attributeName, object userState) {
            if ((this.LeerAtributoDirectorioOperationCompleted == null)) {
                this.LeerAtributoDirectorioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeerAtributoDirectorioOperationCompleted);
            }
            this.InvokeAsync("LeerAtributoDirectorio", new object[] {
                        userName,
                        attributeName}, this.LeerAtributoDirectorioOperationCompleted, userState);
        }
        
        private void OnLeerAtributoDirectorioOperationCompleted(object arg) {
            if ((this.LeerAtributoDirectorioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeerAtributoDirectorioCompleted(this, new LeerAtributoDirectorioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FIELCertificateInfo {
        
        private string serialNumberField;
        
        private System.DateTime expirationDateField;
        
        private bool isActiveField;
        
        private bool isFielCertificateField;
        
        private bool isAutCertificateField;
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFielCertificate {
            get {
                return this.isFielCertificateField;
            }
            set {
                this.isFielCertificateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAutCertificate {
            get {
                return this.isAutCertificateField;
            }
            set {
                this.isAutCertificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserResponse {
        
        private string mailField;
        
        private string passwordField;
        
        private string razonSocialField;
        
        /// <remarks/>
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string RazonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ValidateUserCompletedEventHandler(object sender, ValidateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ValidateUserModuleCompletedEventHandler(object sender, ValidateUserModuleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserModuleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserModuleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ObtenerPerfilCompletedEventHandler(object sender, ObtenerPerfilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPerfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPerfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ObtenerDatosFIELCompletedEventHandler(object sender, ObtenerDatosFIELCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDatosFIELCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDatosFIELCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FIELCertificateInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FIELCertificateInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ObtenNombreRazonSocialCompletedEventHandler(object sender, ObtenNombreRazonSocialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenNombreRazonSocialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenNombreRazonSocialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ObtenDatosUsuarioCompletedEventHandler(object sender, ObtenDatosUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenDatosUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenDatosUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ActualizaMailCompletedEventHandler(object sender, ActualizaMailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizaMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizaMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void VerificarFIELCompletedEventHandler(object sender, VerificarFIELCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarFIELCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarFIELCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void LeerAtributoDirectorioCompletedEventHandler(object sender, LeerAtributoDirectorioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeerAtributoDirectorioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeerAtributoDirectorioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591