//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

namespace SAT.CreditosFiscales.Motor.Entidades.DatosProcesamiento
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class CreditosFiscales
	{

		private CreditosFiscalesDatosGenerales datosGeneralesField;

		private CreditosFiscalesAgrupador[] agrupadoresField;

		private CreditosFiscalesConcepto[] conceptosField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public CreditosFiscalesDatosGenerales DatosGenerales
		{
			get
			{
				return this.datosGeneralesField;
			}
			set
			{
				this.datosGeneralesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Agrupador", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public CreditosFiscalesAgrupador[] Agrupadores
		{
			get
			{
				return this.agrupadoresField;
			}
			set
			{
				this.agrupadoresField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Concepto", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public CreditosFiscalesConcepto[] Conceptos
		{
			get
			{
				return this.conceptosField;
			}
			set
			{
				this.conceptosField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesDatosGenerales
	{

		private string folioField;

		private string rFCField;

		private string rFCGenericoField;

		private string nombreField;

		private string apellidoPaternoField;

		private string apellidoMaternoField;

		private string razonSocialField;

		private sbyte aLRField;

		private int noConceptosField;

		private string idDocumentoField;

		private sbyte tipoDocumentoField;

		private string descripcionDocumentoField;

		private long importeTotalField;

		private string fechaEmisionField;

		private string idContribuyenteField;

		private int idAplicacionField;

		private CreditosFiscalesDatosGeneralesLineasCaptura lineasCapturaField;

		private int numeroParcialidadField;

		private string tipoOperacionField;

		private int deudorPuroField;

		private string observacionesField;

		private string solicitudARectificarField;

		public CreditosFiscalesDatosGenerales()
		{
			this.deudorPuroField = 0;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Folio
		{
			get
			{
				return this.folioField;
			}
			set
			{
				this.folioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string RFC
		{
			get
			{
				return this.rFCField;
			}
			set
			{
				this.rFCField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string RFCGenerico
		{
			get
			{
				return this.rFCGenericoField;
			}
			set
			{
				this.rFCGenericoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Nombre
		{
			get
			{
				return this.nombreField;
			}
			set
			{
				this.nombreField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string ApellidoPaterno
		{
			get
			{
				return this.apellidoPaternoField;
			}
			set
			{
				this.apellidoPaternoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string ApellidoMaterno
		{
			get
			{
				return this.apellidoMaternoField;
			}
			set
			{
				this.apellidoMaternoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string RazonSocial
		{
			get
			{
				return this.razonSocialField;
			}
			set
			{
				this.razonSocialField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public sbyte ALR
		{
			get
			{
				return this.aLRField;
			}
			set
			{
				this.aLRField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int NoConceptos
		{
			get
			{
				return this.noConceptosField;
			}
			set
			{
				this.noConceptosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string IdDocumento
		{
			get
			{
				return this.idDocumentoField;
			}
			set
			{
				this.idDocumentoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public sbyte TipoDocumento
		{
			get
			{
				return this.tipoDocumentoField;
			}
			set
			{
				this.tipoDocumentoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string DescripcionDocumento
		{
			get
			{
				return this.descripcionDocumentoField;
			}
			set
			{
				this.descripcionDocumentoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public long ImporteTotal
		{
			get
			{
				return this.importeTotalField;
			}
			set
			{
				this.importeTotalField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string FechaEmision
		{
			get
			{
				return this.fechaEmisionField;
			}
			set
			{
				this.fechaEmisionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string IdContribuyente
		{
			get
			{
				return this.idContribuyenteField;
			}
			set
			{
				this.idContribuyenteField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int IdAplicacion
		{
			get
			{
				return this.idAplicacionField;
			}
			set
			{
				this.idAplicacionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public CreditosFiscalesDatosGeneralesLineasCaptura LineasCaptura
		{
			get
			{
				return this.lineasCapturaField;
			}
			set
			{
				this.lineasCapturaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int NumeroParcialidad
		{
			get
			{
				return this.numeroParcialidadField;
			}
			set
			{
				this.numeroParcialidadField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string TipoOperacion
		{
			get
			{
				return this.tipoOperacionField;
			}
			set
			{
				this.tipoOperacionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int DeudorPuro
		{
			get
			{
				return this.deudorPuroField;
			}
			set
			{
				this.deudorPuroField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Observaciones
		{
			get
			{
				return this.observacionesField;
			}
			set
			{
				this.observacionesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string SolicitudARectificar
		{
			get
			{
				return this.solicitudARectificarField;
			}
			set
			{
				this.solicitudARectificarField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesDatosGeneralesLineasCaptura
	{

		private CreditosFiscalesDatosGeneralesLineasCapturaDatosLineaCaptura[] datosLineaCapturaField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("DatosLineaCaptura", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public CreditosFiscalesDatosGeneralesLineasCapturaDatosLineaCaptura[] DatosLineaCaptura
		{
			get
			{
				return this.datosLineaCapturaField;
			}
			set
			{
				this.datosLineaCapturaField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesDatosGeneralesLineasCapturaDatosLineaCaptura
	{

		private string lineaCapturaField;

		private long importeField;

		private string fechaVigenciaField;

		private int pagoObligadoInternetField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string LineaCaptura
		{
			get
			{
				return this.lineaCapturaField;
			}
			set
			{
				this.lineaCapturaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public long Importe
		{
			get
			{
				return this.importeField;
			}
			set
			{
				this.importeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string FechaVigencia
		{
			get
			{
				return this.fechaVigenciaField;
			}
			set
			{
				this.fechaVigenciaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int PagoObligadoInternet
		{
			get
			{
				return this.pagoObligadoInternetField;
			}
			set
			{
				this.pagoObligadoInternetField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesAgrupador
	{

		private string numeroAgrupadorField;

		private string fechaField;

		private int autoridadIdField;

		private int aLRField;

		private string rFCField;

		private int saldoInformativoField;

		private string formaPagoField;

		private CreditosFiscalesAgrupadorMarca[] marcasField;

		private CreditosFiscalesAgrupadorConceptos[] conceptosOriginalField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string NumeroAgrupador
		{
			get
			{
				return this.numeroAgrupadorField;
			}
			set
			{
				this.numeroAgrupadorField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Fecha
		{
			get
			{
				return this.fechaField;
			}
			set
			{
				this.fechaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int AutoridadId
		{
			get
			{
				return this.autoridadIdField;
			}
			set
			{
				this.autoridadIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int ALR
		{
			get
			{
				return this.aLRField;
			}
			set
			{
				this.aLRField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string RFC
		{
			get
			{
				return this.rFCField;
			}
			set
			{
				this.rFCField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int SaldoInformativo
		{
			get
			{
				return this.saldoInformativoField;
			}
			set
			{
				this.saldoInformativoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string FormaPago
		{
			get
			{
				return this.formaPagoField;
			}
			set
			{
				this.formaPagoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Marca", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public CreditosFiscalesAgrupadorMarca[] Marcas
		{
			get
			{
				return this.marcasField;
			}
			set
			{
				this.marcasField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Conceptos", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public CreditosFiscalesAgrupadorConceptos[] ConceptosOriginal
		{
			get
			{
				return this.conceptosOriginalField;
			}
			set
			{
				this.conceptosOriginalField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.Serializable()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesAgrupadorMarca
	{

		private string tipoMarcaField;
		private int textField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute("TipoMarca")]
		public string TipoMarca
		{
			get
			{
				return this.tipoMarcaField;
			}
			set
			{
				this.tipoMarcaField = value;
			}
		}

		[System.Xml.Serialization.XmlText()]
		public int Text
		{
			get { return this.textField; }
			set { this.textField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesAgrupadorConceptos
	{
		private int autoridadIdField;

		private string claveField;

		private int ejercicioField;

		private bool ejercicioFieldSpecified;

		private int periodicidadIdField;

		private int periodoIdField;

		private string motivoIdField;

		private string fechaCausacionField;

		private int creditoSirField;

		private string credicoARCAField;

		private decimal importeSinPagoInicialField;

		private decimal importeHistoricoField;

		private decimal importeParteActualizadaField;

		private decimal pagosAnterioresField;

		private bool pagosAnterioresFieldSpecified;

		private decimal importePagarField;

		private string fechaNotificacionField;

		private bool liquidarField;

		private decimal importeTotalCargosField;

		private bool importeTotalCargosFieldSpecified;

		private decimal importeTotalAbonosField;

		private bool importeTotalAbonosFieldSpecified;

		private decimal diferenciaTotalesField;

		private bool diferenciaTotalesFieldSpecified;

		private string formaPagoField;

		private CreditosFiscalesAgrupadorConceptosMarca[] marcasField;

		private CreditosFiscalesAgrupadorConceptosDescuento[] descuentosField;

		private CreditosFiscalesAgrupadorConceptosHijo[] hijosField;

		private bool esCorrectoField;

		private bool esCorrectoFieldSpecified;

		private string tipoMovimientoField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int AutoridadId
		{
			get
			{
				return this.autoridadIdField;
			}
			set
			{
				this.autoridadIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Clave
		{
			get
			{
				return this.claveField;
			}
			set
			{
				this.claveField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int Ejercicio
		{
			get
			{
				return this.ejercicioField;
			}
			set
			{

				this.ejercicioFieldSpecified = true;
				this.ejercicioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool EjercicioSpecified
		{
			get
			{
				return this.ejercicioFieldSpecified;
			}
			set
			{
				this.ejercicioFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int PeriodicidadId
		{
			get
			{
				return this.periodicidadIdField;
			}
			set
			{
				this.periodicidadIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int PeriodoId
		{
			get
			{
				return this.periodoIdField;
			}
			set
			{
				this.periodoIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string MotivoId
		{
			get
			{
				return this.motivoIdField;
			}
			set
			{
				this.motivoIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string FechaCausacion
		{
			get
			{
				return this.fechaCausacionField;
			}
			set
			{
				this.fechaCausacionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int CreditoSir
		{
			get
			{
				return this.creditoSirField;
			}
			set
			{
				this.creditoSirField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string CredicoARCA
		{
			get
			{
				return this.credicoARCAField;
			}
			set
			{
				this.credicoARCAField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImporteSinPagoInicial
		{
			get
			{
				return this.importeSinPagoInicialField;
			}
			set
			{
				this.importeSinPagoInicialField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImporteHistorico
		{
			get
			{
				return this.importeHistoricoField;
			}
			set
			{
				this.importeHistoricoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImporteParteActualizada
		{
			get
			{
				return this.importeParteActualizadaField;
			}
			set
			{
				this.importeParteActualizadaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal PagosAnteriores
		{
			get
			{
				return this.pagosAnterioresField;
			}
			set
			{
				this.pagosAnterioresFieldSpecified = true;
				this.pagosAnterioresField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool PagosAnterioresSpecified
		{
			get
			{
				return this.pagosAnterioresFieldSpecified;
			}
			set
			{
				this.pagosAnterioresFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImportePagar
		{
			get
			{
				return this.importePagarField;
			}
			set
			{
				this.importePagarField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string FechaNotificacion
		{
			get
			{
				return this.fechaNotificacionField;
			}
			set
			{
				this.fechaNotificacionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool Liquidar
		{
			get
			{
				return this.liquidarField;
			}
			set
			{
				this.liquidarField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImporteTotalCargos
		{
			get
			{
				return this.importeTotalCargosField;
			}
			set
			{
				this.importeTotalCargosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ImporteTotalCargosSpecified
		{
			get
			{
				return this.importeTotalCargosFieldSpecified;
			}
			set
			{
				this.importeTotalCargosFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImporteTotalAbonos
		{
			get
			{
				return this.importeTotalAbonosField;
			}
			set
			{
				this.importeTotalAbonosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ImporteTotalAbonosSpecified
		{
			get
			{
				return this.importeTotalAbonosFieldSpecified;
			}
			set
			{
				this.importeTotalAbonosFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal DiferenciaTotales
		{
			get
			{
				return this.diferenciaTotalesField;
			}
			set
			{
				this.diferenciaTotalesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool DiferenciaTotalesSpecified
		{
			get
			{
				return this.diferenciaTotalesFieldSpecified;
			}
			set
			{
				this.diferenciaTotalesFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string FormaPago
		{
			get
			{
				return this.formaPagoField;
			}
			set
			{
				this.formaPagoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Marca", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public CreditosFiscalesAgrupadorConceptosMarca[] Marcas
		{
			get
			{
				return this.marcasField;
			}
			set
			{
				this.marcasField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Descuento", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public CreditosFiscalesAgrupadorConceptosDescuento[] Descuentos
		{
			get
			{
				return this.descuentosField;
			}
			set
			{
				this.descuentosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Hijo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public CreditosFiscalesAgrupadorConceptosHijo[] Hijos
		{
			get
			{
				return this.hijosField;
			}
			set
			{
				this.hijosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool EsCorrecto
		{
			get
			{
				return this.esCorrectoField;
			}
			set
			{
				this.esCorrectoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool EsCorrectoSpecified
		{
			get
			{
				return this.esCorrectoFieldSpecified;
			}
			set
			{
				this.esCorrectoFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string TipoMovimiento
		{
			get
			{
				return this.tipoMovimientoField;
			}
			set
			{
				this.tipoMovimientoField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesAgrupadorConceptosMarca
	{

		private string tipoMarcaField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string TipoMarca
		{
			get
			{
				return this.tipoMarcaField;
			}
			set
			{
				this.tipoMarcaField = value;
			}
		}

		[System.Xml.Serialization.XmlText()]
		public int Text { get; set; }
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesAgrupadorConceptosDescuento
	{

		private string idDescuentoField;

		private decimal importeDescuentoField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string IdDescuento
		{
			get
			{
				return this.idDescuentoField;
			}
			set
			{
				this.idDescuentoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImporteDescuento
		{
			get
			{
				return this.importeDescuentoField;
			}
			set
			{
				this.importeDescuentoField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesAgrupadorConceptosHijo
	{
		private int autoridadIdField;

		private string claveField;

		private string motivoIdField;

		private string fechaCausacionField;

		private int creditoSirField;

		private decimal importeSinPagoInicialField;

		private decimal importeHistoricoField;

		private decimal importeParteActualizadaField;

		private decimal pagosAnterioresField;

		private bool pagosAnterioresFieldSpecified;

		private decimal importePagarField;

		private string fechaNotificacionField;

		private int ejercicioField;

		private bool ejercicioFieldSpecified;

		private int periodicidadIdField;

		private int periodoIdField;

		private bool liquidarField;

		private decimal importeTotalCargosField;

		private bool importeTotalCargosFieldSpecified;

		private decimal importeTotalAbonosField;

		private bool importeTotalAbonosFieldSpecified;

		private decimal diferenciaTotalesField;

		private bool diferenciaTotalesFieldSpecified;

		private string formaPagoField;

		private string tipoTransaccionField;

		private CreditosFiscalesAgrupadorConceptosHijoMarca[] marcasField;

		private CreditosFiscalesAgrupadorConceptosHijoDescuento[] descuentosField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int AutoridadId
		{
			get
			{
				return this.autoridadIdField;
			}
			set
			{
				this.autoridadIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Clave
		{
			get
			{
				return this.claveField;
			}
			set
			{
				this.claveField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string MotivoId
		{
			get
			{
				return this.motivoIdField;
			}
			set
			{
				this.motivoIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string FechaCausacion
		{
			get
			{
				return this.fechaCausacionField;
			}
			set
			{
				this.fechaCausacionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int CreditoSir
		{
			get
			{
				return this.creditoSirField;
			}
			set
			{
				this.creditoSirField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImporteSinPagoInicial
		{
			get
			{
				return this.importeSinPagoInicialField;
			}
			set
			{
				this.importeSinPagoInicialField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImporteHistorico
		{
			get
			{
				return this.importeHistoricoField;
			}
			set
			{
				this.importeHistoricoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImporteParteActualizada
		{
			get
			{
				return this.importeParteActualizadaField;
			}
			set
			{
				this.importeParteActualizadaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal PagosAnteriores
		{
			get
			{
				return this.pagosAnterioresField;
			}
			set
			{
				this.pagosAnterioresFieldSpecified = true;
				this.pagosAnterioresField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool PagosAnterioresSpecified
		{
			get
			{
				return this.pagosAnterioresFieldSpecified;
			}
			set
			{
				this.pagosAnterioresFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImportePagar
		{
			get
			{
				return this.importePagarField;
			}
			set
			{
				this.importePagarField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string FechaNotificacion
		{
			get
			{
				return this.fechaNotificacionField;
			}
			set
			{
				this.fechaNotificacionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int Ejercicio
		{
			get
			{
				return this.ejercicioField;
			}
			set
			{
				this.ejercicioFieldSpecified = true;
				this.ejercicioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool EjercicioSpecified
		{
			get
			{
				return this.ejercicioFieldSpecified;
			}
			set
			{
				this.ejercicioFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int PeriodicidadId
		{
			get
			{
				return this.periodicidadIdField;
			}
			set
			{
				this.periodicidadIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int PeriodoId
		{
			get
			{
				return this.periodoIdField;
			}
			set
			{
				this.periodoIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool Liquidar
		{
			get
			{
				return this.liquidarField;
			}
			set
			{
				this.liquidarField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImporteTotalCargos
		{
			get
			{
				return this.importeTotalCargosField;
			}
			set
			{
				this.importeTotalCargosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ImporteTotalCargosSpecified
		{
			get
			{
				return this.importeTotalCargosFieldSpecified;
			}
			set
			{
				this.importeTotalCargosFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImporteTotalAbonos
		{
			get
			{
				return this.importeTotalAbonosField;
			}
			set
			{
				this.importeTotalAbonosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ImporteTotalAbonosSpecified
		{
			get
			{
				return this.importeTotalAbonosFieldSpecified;
			}
			set
			{
				this.importeTotalAbonosFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal DiferenciaTotales
		{
			get
			{
				return this.diferenciaTotalesField;
			}
			set
			{
				this.diferenciaTotalesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool DiferenciaTotalesSpecified
		{
			get
			{
				return this.diferenciaTotalesFieldSpecified;
			}
			set
			{
				this.diferenciaTotalesFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string FormaPago
		{
			get
			{
				return this.formaPagoField;
			}
			set
			{
				this.formaPagoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string TipoTransaccion
		{
			get
			{
				return this.tipoTransaccionField;
			}
			set
			{
				this.tipoTransaccionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Marca", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public CreditosFiscalesAgrupadorConceptosHijoMarca[] Marcas
		{
			get
			{
				return this.marcasField;
			}
			set
			{
				this.marcasField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Descuento", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public CreditosFiscalesAgrupadorConceptosHijoDescuento[] Descuentos
		{
			get
			{
				return this.descuentosField;
			}
			set
			{
				this.descuentosField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesAgrupadorConceptosHijoMarca
	{

		private string tipoMarcaField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string TipoMarca
		{
			get
			{
				return this.tipoMarcaField;
			}
			set
			{
				this.tipoMarcaField = value;
			}
		}

		[System.Xml.Serialization.XmlText()]
		public int Text { get; set; }
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesAgrupadorConceptosHijoDescuento
	{

		private string idDescuentoField;

		private decimal importeDescuentoField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string IdDescuento
		{
			get
			{
				return this.idDescuentoField;
			}
			set
			{
				this.idDescuentoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImporteDescuento
		{
			get
			{
				return this.importeDescuentoField;
			}
			set
			{
				this.importeDescuentoField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesConcepto
	{
		private int idAplicacion;

		private bool esCorrectoField;

		private bool esCorrectoFieldSpecified;

		private int idAgrupadorField;

		private short noSecuenciaField;

		private string claveField;

		private string descripcionField;

		private int ejercicioField;

		private bool ejercicioFieldSpecified;

		private string claveOrigenField;

		private string tipoPeriodicidadField;

		private string periodicidadField;

		private string clavePeriodoField;

		private int numeroCreditoField;

		private string periodoField;

		private decimal importePagarField;

		private string fechaCausacionField;

		private CreditosFiscalesConceptoTransaccion[] transaccionesField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int IdAplicacion
		{
			get
			{
				return this.idAplicacion;
			}
			set
			{
				this.idAplicacion = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool EsCorrecto
		{
			get
			{
				return this.esCorrectoField;
			}
			set
			{
				this.esCorrectoFieldSpecified = true;
				this.esCorrectoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool EsCorrectoSpecified
		{
			get
			{
				return this.esCorrectoFieldSpecified;
			}
			set
			{
				this.esCorrectoFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int IdAgrupador
		{
			get
			{
				return this.idAgrupadorField;
			}
			set
			{
				this.idAgrupadorField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public short NoSecuencia
		{
			get
			{
				return this.noSecuenciaField;
			}
			set
			{
				this.noSecuenciaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Clave
		{
			get
			{
				return this.claveField;
			}
			set
			{
				this.claveField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Descripcion
		{
			get
			{
				return this.descripcionField;
			}
			set
			{
				this.descripcionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int Ejercicio
		{
			get
			{
				return this.ejercicioField;
			}
			set
			{
				this.ejercicioFieldSpecified = true;
				this.ejercicioField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool EjercicioSpecified
		{
			get
			{
				return this.ejercicioFieldSpecified;
			}
			set
			{
				this.ejercicioFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string ClaveOrigen
		{
			get
			{
				return this.claveOrigenField;
			}
			set
			{
				this.claveOrigenField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string TipoPeriodicidad
		{
			get
			{
				return this.tipoPeriodicidadField;
			}
			set
			{
				this.tipoPeriodicidadField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Periodicidad
		{
			get
			{
				return this.periodicidadField;
			}
			set
			{
				this.periodicidadField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string ClavePeriodo
		{
			get
			{
				return this.clavePeriodoField;
			}
			set
			{
				this.clavePeriodoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int NumeroCredito
		{
			get
			{
				return this.numeroCreditoField;
			}
			set
			{
				this.numeroCreditoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Periodo
		{
			get
			{
				return this.periodoField;
			}
			set
			{
				this.periodoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal ImportePagar
		{
			get
			{
				return this.importePagarField;
			}
			set
			{
				this.importePagarField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string FechaCausacion
		{
			get
			{
				return this.fechaCausacionField;
			}
			set
			{
				this.fechaCausacionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Transaccion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public CreditosFiscalesConceptoTransaccion[] Transacciones
		{
			get
			{
				return this.transaccionesField;
			}
			set
			{
				this.transaccionesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesConceptoTransaccion
	{

		private string claveField;

		private string descripcionField;

		private long importeField;

		private string tipoField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Clave
		{
			get
			{
				return this.claveField;
			}
			set
			{
				this.claveField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Descripcion
		{
			get
			{
				return this.descripcionField;
			}
			set
			{
				this.descripcionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public long Importe
		{
			get
			{
				return this.importeField;
			}
			set
			{
				this.importeField = value;
			}
		}

		/// <remarks/>
		[XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Tipo
		{
			get
			{
				return this.tipoField;
			}
			set
			{
				this.tipoField = value;
			}
		}
	}
}