USE ManejoRMA
GO
INSERT INTO Tablas (Tabla, Estado) VALUES('Tipos Requerimientos', 1)
INSERT INTO Tablas (Tabla, Estado) VALUES('Estados RMA', 1)
INSERT INTO Tablas (Tabla, Estado) VALUES('Area', 1)
INSERT INTO Tablas (Tabla, Estado) VALUES('Estados RDL', 1)
INSERT INTO Tablas (Tabla, Estado) VALUES('ResponsableRDL', 1)
INSERT INTO Tablas (Tabla, Estado) VALUES('Aplicativos', 1)
INSERT INTO Tablas (Tabla, Estado) VALUES('Repositorio', 1)
GO
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(1, 'RMA', 0, 'RMA', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(1, 'POL', 0, 'POL', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(2, 'Reg', 0, 'Registrado', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(2, 'Cur', 0, 'Curso', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(2, 'Paq', 0, 'Paquete', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(2, 'Rech', 0, 'Rechazado', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(2, 'CanInt', 0, 'Cancelado', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(3, '', 0, 'APE4', 'APE4', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(3, '', 0, 'APE1', 'APE4', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(3, '', 0, 'APE2', 'APE4', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(3, '', 0, 'Azure', 'APE4', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 16, 'Registro RDL', 'Softtek', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 17, 'Verificacion Desarrollo', 'RAPE', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 18, 'Recepción Versiones', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 19, 'Verificación Desarrollo (Corrección)', 'RAPE', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 21, 'Rechazo a Rape', 'RAPE', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 23, 'Cerrado (Corrección Desarrollo AD)', 'Softtek', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 31, 'Pruebas Concluidas (AVL) - Avance Liberación ', 'Operaciones', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 38, 'Cerrado Liberación Normal (Instalacion Concluida)', 'Softtek', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 49, 'Cerrado (Cancelado)', 'RAPE', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 55, 'Notificación y Pruebas de Usuario', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 91, 'Incidencias Liberación', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 92, 'Recepción Operaciones', 'Operaciones', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 93, 'Recepción Operaciones SSO', 'Operaciones', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 98, 'Incidencias de Laboratorio por parte de Versiones', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 100, 'Falta descripcion', '???', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 127, 'Verificacion-Compilación-Armado ', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 130, 'Validacion -AVL (PM y/o Torre)', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 131, 'Validacion-AVL (ReInstalacion)', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 200, 'Rechazo a Armado de Paquetes', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 400, 'Validación Rechazo (FSW)', 'Softtek', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 444, 'Cerrado (Servicio de Compilacion)', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 500, 'Registro Nueva RDL (Corrección Desarrollo AD)', 'Softtek', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 505, 'Registro Nueva RDL (Incidencias Desarrollo)', 'Softtek', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 508, 'Validación Rechazo (FSW)(RECHAZO OPERACIONES)', 'Softtek', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 550, 'Pruebas Funcionales SN', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 551, 'Ejecución de Pruebas', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 552, 'En Espera de Nota de Liberacion', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 553, 'Validacion', 'Sol Neg', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 602, 'RdL Relacionada', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 701, 'Recepción Instalación', 'Operaciones', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 702, 'Instalación Configuración (LAB)', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 704, 'Instalación Configuración Concluida (LAB)', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 705, 'Validación Técnico Funcional  (LAB)', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 706, 'Instalación Erronea ', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 710, 'Torres AVL', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 711, 'Torres Externas(Proveedores)', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 712, 'Gestíón de Cambios UAT', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 713, 'Torres Operacion UAT', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 714, 'Programado', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 715, 'Recepcion Operacion UAT(Proveedores)', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 716, 'Incidencias UAT-Instalacion ', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 717, 'Torres Externas SSO', 'Operaciones', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 724, 'Programado(SAT) (Sin Fecha Prg)', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 730, 'Azure(Nube)-UAT', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 788, 'Instalación AVL ', 'AVL', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 900, 'Gestión de Cambios', 'Operaciones', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(4, '', 902, 'Instalación Concluida', 'Operaciones', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(6, '', 12, 'CUN WEB CONSULTA DE DECLARACIONES Y PAGOS WEB', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(6, '', 104, 'MONITOR DE LOTES MODELO (NEPE)', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(6, '', 105, 'NEPE NUEVO ESQUEMA DE PAGOS ELECTRONICOS', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(6, '', 335, 'DIOT DECLARACION INFORMATIVA DE OPERACIONES CON TERCEROS', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(6, '', 382, 'DEC_IDE', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(6, '', 404, 'FORMA R15', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(6, '', 81, 'CONTABILIDAD NEPE', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(6, '', 417, 'VALIDADOR DE INTERESES', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(6, '', 416, 'VALIDADOR DE FIDEICOMISOS', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(6, '', 125, 'FORMA 35 DECLARACION INFORMATIVA', '', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(7, '', 12, 'dyp_pp_cun-web', 'https://gitlab.sat.gob.mx/avl/[REP]|https://gitlab.sat.gob.mx/avl/[REP]|http://18.144.132.20/proyectos/sat/sdma6/ape1/dyp/[REP]/-/tree/main/Continuidad%20Operativa/Incidencias/RMA-[RMA]/[PAQ]', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(7, '', 105, 'dyp_lda_nepe', 'https://gitlab.sat.gob.mx/avl/[REP]|https://gitlab.sat.gob.mx/avl/[REP]|http://18.144.132.20/proyectos/sat/sdma6/ape1/dyp/[REP]/-/tree/main/Continuidad%20Operativa/Incidencias/RMA-[RMA]/[PAQ]', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(7, '', 355, 'dyp_pp_diot', 'https://gitlab.sat.gob.mx/avl/[REP]|http://18.144.132.20/proyectos/sat/sdma6/ape1/dyp/[REP]/-/tree/main/Continuidad%20Operativa/Incidencias/RMA-[RMA]/[PAQ]', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(7, '', 104, 'dyp_lda_modelo', 'https://gitlab.sat.gob.mx/avl/[REP]|https://gitlab.sat.gob.mx/avl/[REP]|http://18.144.132.20/proyectos/sat/sdma6/ape1/dyp/[REP]/-/tree/main/Continuidad%20Operativa/Incidencias/RMA-[RMA]/[PAQ]', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(7, '', 382, 'dyp_pp_dec_ide', 'https://gitlab.sat.gob.mx/avl/[REP]|https://gitlab.sat.gob.mx/avl/[REP]|http://18.144.132.20/proyectos/sat/sdma6/ape1/dyp/[REP]/-/tree/main/Continuidad%20Operativa/Incidencias/RMA-[RMA]/[PAQ]', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(7, '', 404, 'dyp_pp_forma_r15', 'https://gitlab.sat.gob.mx/avl/[REP]|https://gitlab.sat.gob.mx/avl/[REP]|http://18.144.132.20/proyectos/sat/sdma6/ape1/dyp/[REP]/-/tree/main/Continuidad%20Operativa/Incidencias/RMA-[RMA]/[PAQ]', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(7, '', 81, 'rc_contabilidad_nepe', 'https://gitlab.sat.gob.mx/avl/[REP]|https://gitlab.sat.gob.mx/avl/[REP]|http://18.144.132.20/proyectos/sat/sdma6/ape1/dyp/[REP]/-/tree/main/Continuidad%20Operativa/Incidencias/RMA-[RMA]/[PAQ]', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(7, '', 417, 'dyp_lda_validador_de_intereses', 'https://gitlab.sat.gob.mx/avl/[REP]|https://gitlab.sat.gob.mx/avl/[REP]|http://18.144.132.20/proyectos/sat/sdma6/ape1/dyp/[REP]/-/tree/main/Continuidad%20Operativa/Incidencias/RMA-[RMA]/[PAQ]', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(7, '', 416, 'dyp_lda_validador_de_fideicomisos', 'https://gitlab.sat.gob.mx/avl/[REP]|https://gitlab.sat.gob.mx/avl/[REP]|http://18.144.132.20/proyectos/sat/sdma6/ape1/dyp/[REP]/-/tree/main/Continuidad%20Operativa/Incidencias/RMA-[RMA]/[PAQ]', 1)
INSERT INTO TablasDetalles (nIdTabla, Acronimo, Orden, TablaDetalle, Observaciones, Estado) VALUES(7, '', 125, 'dyp_pp_forma_35', 'https://gitlab.sat.gob.mx/avl/[REP]|https://gitlab.sat.gob.mx/avl/[REP]|http://18.144.132.20/proyectos/sat/sdma6/ape1/dyp/[REP]/-/tree/main/Continuidad%20Operativa/Incidencias/RMA-[RMA]/[PAQ]', 1)
GO
INSERT INTO Empleados (nIdArea, nIdAplicativo, sNombre, sApellido1, sApellido2, sUsuario, sContra, Orden, Root, Estado) VALUES(8, null, 'ISAAC', 'DIAS', 'VARGAS', 'idias', 'oEFPCa1Z1k+qV2t65a98yA==', 3, 0, 1)
INSERT INTO Empleados (nIdArea, nIdAplicativo, sNombre, sApellido1, sApellido2, sUsuario, sContra, Orden, Root, Estado) VALUES(8, null, 'JOSE ANTONIO', 'MENDOSA', 'SALASAR', 'jmendosa', 'oEFPCa1Z1k+qV2t65a98yA==', 4, 0, 1)
INSERT INTO Empleados (nIdArea, nIdAplicativo, sNombre, sApellido1, sApellido2, sUsuario, sContra, Orden, Root, Estado) VALUES(8, null, 'ARTURO EFRAIN', 'MINGUES', 'ALCANTARA', 'amingues', 'oEFPCa1Z1k+qV2t65a98yA==', 1, 1, 1)
INSERT INTO Empleados (nIdArea, nIdAplicativo, sNombre, sApellido1, sApellido2, sUsuario, sContra, Orden, Root, Estado) VALUES(8, null, 'MANUEL FRANCISCO ', 'MUÑOS', 'CALVO', 'mmuños', 'oEFPCa1Z1k+qV2t65a98yA==', 2, 1, 1)
INSERT INTO Empleados (nIdArea, nIdAplicativo, sNombre, sApellido1, sApellido2, sUsuario, sContra, Orden, Root, Estado) VALUES(8, null, 'ANGEL', 'RAMIREZ', 'MANCERA', 'aramirez', 'oEFPCa1Z1k+qV2t65a98yA==', 6, 1, 1)
INSERT INTO Empleados (nIdArea, nIdAplicativo, sNombre, sApellido1, sApellido2, sUsuario, sContra, Orden, Root, Estado) VALUES(8, null, 'JACOB ADIEL', 'GARCIA', 'GARCIA', 'jgarcia', 'oEFPCa1Z1k+qV2t65a98yA==', 5, 0, 1)
GO
INSERT INTO EmpleadoArea (nIdEmpleado, nIdArea) VALUES(1, 8)
INSERT INTO EmpleadoArea (nIdEmpleado, nIdArea) VALUES(2, 8)
INSERT INTO EmpleadoArea (nIdEmpleado, nIdArea) VALUES(3, 8)
INSERT INTO EmpleadoArea (nIdEmpleado, nIdArea) VALUES(4, 8)
INSERT INTO EmpleadoArea (nIdEmpleado, nIdArea) VALUES(5, 8)
INSERT INTO EmpleadoArea (nIdEmpleado, nIdArea) VALUES(6, 8)
GO
INSERT INTO AreaAplicativo (nIdArea, nIdAplicativo) VALUES(8, 59)
INSERT INTO AreaAplicativo (nIdArea, nIdAplicativo) VALUES(8, 60)
INSERT INTO AreaAplicativo (nIdArea, nIdAplicativo) VALUES(8, 61)
INSERT INTO AreaAplicativo (nIdArea, nIdAplicativo) VALUES(8, 62)
INSERT INTO AreaAplicativo (nIdArea, nIdAplicativo) VALUES(8, 63)
GO