//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProDec_ReglaNegocio.IdeValidacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IdeValidacion.IValidacion")]
    public interface IValidacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacion/iniciarValidacion", ReplyAction="http://tempuri.org/IValidacion/iniciarValidacionResponse")]
        void iniciarValidacion(int folio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValidacionChannel : ProDec_ReglaNegocio.IdeValidacion.IValidacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidacionClient : System.ServiceModel.ClientBase<ProDec_ReglaNegocio.IdeValidacion.IValidacion>, ProDec_ReglaNegocio.IdeValidacion.IValidacion {
        
        public ValidacionClient() {
        }
        
        public ValidacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void iniciarValidacion(int folio) {
            base.Channel.iniciarValidacion(folio);
        }
    }
}
