//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
[Serializable]
public partial class RespuestaLC : ISerializable
{
    private string idProcesamientoField;

    private RespuestaLCDatosLinea[] lineasCapturaField;

    private string[] listaErroresField;

    private int tipoRespuestaField;

    private byte[] pDFField;

    public RespuestaLC()
    {
        
    }

    public RespuestaLC(SerializationInfo info, StreamingContext context)
    {
        LineasCaptura = info.GetValue("LineasCaptura",typeof(RespuestaLCDatosLinea)) as RespuestaLCDatosLinea[];
        ListaErrores = info.GetValue("ListaErrores", typeof (string[])) as string[];
        TipoRespuesta = info.GetInt32("TipoRespuesta");
        PDF = info.GetValue("PDF", typeof (byte[])) as byte[];
        IdProcesamiento = info.GetString("IdProcesamiento");
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DatosLinea", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public RespuestaLCDatosLinea[] LineasCaptura
    {
        get
        {
            return this.lineasCapturaField;
        }
        set
        {
            this.lineasCapturaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Error", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public string[] ListaErrores
    {
        get
        {
            return this.listaErroresField;
        }
        set
        {
            this.listaErroresField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int TipoRespuesta
    {
        get
        {
            return this.tipoRespuestaField;
        }
        set
        {
            this.tipoRespuestaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary")]
    public byte[] PDF
    {
        get
        {
            return this.pDFField;
        }
        set
        {
            this.pDFField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdProcesamiento
    {
        get
        {
            return this.idProcesamientoField;
        }
        set
        {
            this.idProcesamientoField = value;
        }
    }

    public void GetObjectData(SerializationInfo info, StreamingContext context)
    {
        info.AddValue("IdProcesamiento", IdProcesamiento);
        info.AddValue("PDF",PDF);
        info.AddValue("TipoRespuesta", TipoRespuesta);
        info.AddValue("ListaErrores", ListaErrores);
        info.AddValue("LineasCaptura", LineasCaptura);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[Serializable]
public partial class RespuestaLCDatosLinea : ISerializable
{

    private string folioField;

    private string lineaCapturaField;

    public RespuestaLCDatosLinea(SerializationInfo info, StreamingContext context)
    {
        Folio = info.GetString("Folio");
        LineaCaptura = info.GetString("LineaCaptura");
    }

    public RespuestaLCDatosLinea()
    {
        
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Folio
    {
        get
        {
            return this.folioField;
        }
        set
        {
            this.folioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LineaCaptura
    {
        get
        {
            return this.lineaCapturaField;
        }
        set
        {
            this.lineaCapturaField = value;
        }
    }

    public void GetObjectData(SerializationInfo info, StreamingContext context)
    {
        info.AddValue("Folio", Folio);
        info.AddValue("LineaCaptura", LineaCaptura);



    }
}