//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18052
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sat.CreditosFiscales.Procesamiento.LogicaNegocio.ServicioTraductorLC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioTraductorLC.ICreditosFiscales")]
    public interface ICreditosFiscales {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditosFiscales/ObtieneLineaCaptura", ReplyAction="http://tempuri.org/ICreditosFiscales/ObtieneLineaCapturaResponse")]
        string ObtieneLineaCaptura(short idAplicacion, short idTipoDoc, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditosFiscales/ObtieneLineaCapturaConPDF", ReplyAction="http://tempuri.org/ICreditosFiscales/ObtieneLineaCapturaConPDFResponse")]
        string ObtieneLineaCapturaConPDF(short idAplicacion, short idTipoDoc, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditosFiscales/ConsultaLineasCapturaXDocumento", ReplyAction="http://tempuri.org/ICreditosFiscales/ConsultaLineasCapturaXDocumentoResponse")]
        string ConsultaLineasCapturaXDocumento(string documentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditosFiscales/ObtieneDocumentosEnLineaCaptura", ReplyAction="http://tempuri.org/ICreditosFiscales/ObtieneDocumentosEnLineaCapturaResponse")]
        string ObtieneDocumentosEnLineaCaptura(string lineaCaptura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditosFiscales/ObtieneXMLOriginal", ReplyAction="http://tempuri.org/ICreditosFiscales/ObtieneXMLOriginalResponse")]
        string ObtieneXMLOriginal(string Folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditosFiscales/ObtieneListaFolios", ReplyAction="http://tempuri.org/ICreditosFiscales/ObtieneListaFoliosResponse")]
        string ObtieneListaFolios(string RFC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditosFiscalesChannel : Sat.CreditosFiscales.Procesamiento.LogicaNegocio.ServicioTraductorLC.ICreditosFiscales, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditosFiscalesClient : System.ServiceModel.ClientBase<Sat.CreditosFiscales.Procesamiento.LogicaNegocio.ServicioTraductorLC.ICreditosFiscales>, Sat.CreditosFiscales.Procesamiento.LogicaNegocio.ServicioTraductorLC.ICreditosFiscales {
        
        public CreditosFiscalesClient() {
        }
        
        public CreditosFiscalesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditosFiscalesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditosFiscalesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditosFiscalesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtieneLineaCaptura(short idAplicacion, short idTipoDoc, string documento) {
            return base.Channel.ObtieneLineaCaptura(idAplicacion, idTipoDoc, documento);
        }
        
        public string ObtieneLineaCapturaConPDF(short idAplicacion, short idTipoDoc, string documento) {
            return base.Channel.ObtieneLineaCapturaConPDF(idAplicacion, idTipoDoc, documento);
        }
        
        public string ConsultaLineasCapturaXDocumento(string documentos) {
            return base.Channel.ConsultaLineasCapturaXDocumento(documentos);
        }
        
        public string ObtieneDocumentosEnLineaCaptura(string lineaCaptura) {
            return base.Channel.ObtieneDocumentosEnLineaCaptura(lineaCaptura);
        }
        
        public string ObtieneXMLOriginal(string Folio) {
            return base.Channel.ObtieneXMLOriginal(Folio);
        }
        
        public string ObtieneListaFolios(string RFC) {
            return base.Channel.ObtieneListaFolios(RFC);
        }
    }
}
