
//@(#)SCADE2(W:SKDN08221CO2:SAT.DyP.Routing.Configuration.Client:ConfigurationService:0:21/May/2008[SAT.DyP.Routing.Configuration.Client:1.0:21/May/2008])
	
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.DyP.Routing.Configuration.Client.ConfigurationService {
    using System.Runtime.Serialization;
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.sat.gob.mx/scade.net/2007_10_07/routing")]
    [System.SerializableAttribute()]
    public partial class RouteMessage : object, System.Runtime.Serialization.IExtensibleDataObject {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IDRouteField;

        private string SoapActionField;

        private string DestinationField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int IDRoute {
            get {
                return this.IDRouteField;
            }
            set {
                this.IDRouteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string SoapAction {
            get {
                return this.SoapActionField;
            }
            set {
                this.SoapActionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public string Destination {
            get {
                return this.DestinationField;
            }
            set {
                this.DestinationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                this.DescriptionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.sat.gob.mx/scade.net/2007_10_07/routing")]
    [System.SerializableAttribute()]
    public partial class DefaultFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int ErrorIdField;

        private string ErrorMessageField;

        private System.Guid CorrelationIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int ErrorId {
            get {
                return this.ErrorIdField;
            }
            set {
                this.ErrorIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                this.ErrorMessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public System.Guid CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                this.CorrelationIdField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.sat.gob.mx/scade.net/2007_10_07/routing", ConfigurationName = "Routing.Configuration.Client.ConfigurationService.IConfigurationService")]
    public interface IConfigurationService {

        [System.ServiceModel.OperationContractAttribute(Action = "GetAllRoutes", ReplyAction = "http://www.sat.gob.mx/scade.net/2007_10_07/routing/IConfigurationService/GetAllRo" +
            "utesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Routing.Configuration.Client.ConfigurationService.DefaultFaultContract), Action = "http://www.sat.gob.mx/scade.net/2007_10_07/routing/IConfigurationService/GetAllRo" +
            "utesDefaultFaultContractFault", Name = "DefaultFaultContract")]
        Routing.Configuration.Client.ConfigurationService.RouteMessage[] GetAllRoutes();

        [System.ServiceModel.OperationContractAttribute(Action = "GetRoute", ReplyAction = "http://www.sat.gob.mx/scade.net/2007_10_07/routing/IConfigurationService/GetRoute" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Routing.Configuration.Client.ConfigurationService.DefaultFaultContract), Action = "http://www.sat.gob.mx/scade.net/2007_10_07/routing/IConfigurationService/GetRoute" +
            "DefaultFaultContractFault", Name = "DefaultFaultContract")]
        Routing.Configuration.Client.ConfigurationService.RouteMessage GetRoute(int request);

        [System.ServiceModel.OperationContractAttribute(Action = "AddRoute", ReplyAction = "http://www.sat.gob.mx/scade.net/2007_10_07/routing/IConfigurationService/AddRoute" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Routing.Configuration.Client.ConfigurationService.DefaultFaultContract), Action = "http://www.sat.gob.mx/scade.net/2007_10_07/routing/IConfigurationService/AddRoute" +
            "DefaultFaultContractFault", Name = "DefaultFaultContract")]
        void AddRoute(Routing.Configuration.Client.ConfigurationService.RouteMessage request);

        [System.ServiceModel.OperationContractAttribute(Action = "DeleteRoute", ReplyAction = "http://www.sat.gob.mx/scade.net/2007_10_07/routing/IConfigurationService/DeleteRo" +
            "uteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Routing.Configuration.Client.ConfigurationService.DefaultFaultContract), Action = "http://www.sat.gob.mx/scade.net/2007_10_07/routing/IConfigurationService/DeleteRo" +
            "uteDefaultFaultContractFault", Name = "DefaultFaultContract")]
        void DeleteRoute(int request);

        [System.ServiceModel.OperationContractAttribute(Action = "SaveRoute", ReplyAction = "http://www.sat.gob.mx/scade.net/2007_10_07/routing/IConfigurationService/SaveRout" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Routing.Configuration.Client.ConfigurationService.DefaultFaultContract), Action = "http://www.sat.gob.mx/scade.net/2007_10_07/routing/IConfigurationService/SaveRout" +
            "eDefaultFaultContractFault", Name = "DefaultFaultContract")]
        void SaveRoute(Routing.Configuration.Client.ConfigurationService.RouteMessage request);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IConfigurationServiceChannel : Routing.Configuration.Client.ConfigurationService.IConfigurationService, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ConfigurationServiceClient : System.ServiceModel.ClientBase<Routing.Configuration.Client.ConfigurationService.IConfigurationService>, Routing.Configuration.Client.ConfigurationService.IConfigurationService {

        public ConfigurationServiceClient() {
        }

        public ConfigurationServiceClient(string endpointConfigurationName)
            :
                base(endpointConfigurationName) {
        }

        public ConfigurationServiceClient(string endpointConfigurationName, string remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress) {
        }

        public ConfigurationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress) {
        }

        public ConfigurationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(binding, remoteAddress) {
        }

        public Routing.Configuration.Client.ConfigurationService.RouteMessage[] GetAllRoutes() {
            return base.Channel.GetAllRoutes();
        }

        public Routing.Configuration.Client.ConfigurationService.RouteMessage GetRoute(int request) {
            return base.Channel.GetRoute(request);
        }

        public void AddRoute(Routing.Configuration.Client.ConfigurationService.RouteMessage request) {
            base.Channel.AddRoute(request);
        }

        public void DeleteRoute(int request) {
            base.Channel.DeleteRoute(request);
        }

        public void SaveRoute(Routing.Configuration.Client.ConfigurationService.RouteMessage request) {
            base.Channel.SaveRoute(request);
        }
    }
}

