//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3625.
// 
#pragma warning disable 1591

namespace SAT.DyP.Util.Security.wsSgiHelper {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsSgiHelperSoap", Namespace="http://tempuri.org/")]
    public partial class wsSgiHelper : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EsFirmaValidaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarSelloDigitalOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarFIELContribuyenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCertificadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DesencriptarDeclaracionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsSgiHelper() {
            this.Url = global::SAT.DyP.Util.Security.Properties.Settings.Default.SAT_SCADE_NET_Common_Security_wsSgiHelper_wsSgiHelper;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EsFirmaValidaCompletedEventHandler EsFirmaValidaCompleted;
        
        /// <remarks/>
        public event GenerarSelloDigitalCompletedEventHandler GenerarSelloDigitalCompleted;
        
        /// <remarks/>
        public event VerificarFIELContribuyenteCompletedEventHandler VerificarFIELContribuyenteCompleted;
        
        /// <remarks/>
        public event ObtenerCertificadoCompletedEventHandler ObtenerCertificadoCompleted;
        
        /// <remarks/>
        public event DesencriptarDeclaracionCompletedEventHandler DesencriptarDeclaracionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EsFirmaValida", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EsFirmaValida(string numeroSerie, string cadenaOriginal, string selloDigital) {
            object[] results = this.Invoke("EsFirmaValida", new object[] {
                        numeroSerie,
                        cadenaOriginal,
                        selloDigital});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EsFirmaValidaAsync(string numeroSerie, string cadenaOriginal, string selloDigital) {
            this.EsFirmaValidaAsync(numeroSerie, cadenaOriginal, selloDigital, null);
        }
        
        /// <remarks/>
        public void EsFirmaValidaAsync(string numeroSerie, string cadenaOriginal, string selloDigital, object userState) {
            if ((this.EsFirmaValidaOperationCompleted == null)) {
                this.EsFirmaValidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEsFirmaValidaOperationCompleted);
            }
            this.InvokeAsync("EsFirmaValida", new object[] {
                        numeroSerie,
                        cadenaOriginal,
                        selloDigital}, this.EsFirmaValidaOperationCompleted, userState);
        }
        
        private void OnEsFirmaValidaOperationCompleted(object arg) {
            if ((this.EsFirmaValidaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EsFirmaValidaCompleted(this, new EsFirmaValidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarSelloDigital", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerarSelloDigital(string cadenaOriginal) {
            object[] results = this.Invoke("GenerarSelloDigital", new object[] {
                        cadenaOriginal});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarSelloDigitalAsync(string cadenaOriginal) {
            this.GenerarSelloDigitalAsync(cadenaOriginal, null);
        }
        
        /// <remarks/>
        public void GenerarSelloDigitalAsync(string cadenaOriginal, object userState) {
            if ((this.GenerarSelloDigitalOperationCompleted == null)) {
                this.GenerarSelloDigitalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarSelloDigitalOperationCompleted);
            }
            this.InvokeAsync("GenerarSelloDigital", new object[] {
                        cadenaOriginal}, this.GenerarSelloDigitalOperationCompleted, userState);
        }
        
        private void OnGenerarSelloDigitalOperationCompleted(object arg) {
            if ((this.GenerarSelloDigitalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarSelloDigitalCompleted(this, new GenerarSelloDigitalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificarFIELContribuyente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerificarFIELContribuyente(string rfc) {
            object[] results = this.Invoke("VerificarFIELContribuyente", new object[] {
                        rfc});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarFIELContribuyenteAsync(string rfc) {
            this.VerificarFIELContribuyenteAsync(rfc, null);
        }
        
        /// <remarks/>
        public void VerificarFIELContribuyenteAsync(string rfc, object userState) {
            if ((this.VerificarFIELContribuyenteOperationCompleted == null)) {
                this.VerificarFIELContribuyenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarFIELContribuyenteOperationCompleted);
            }
            this.InvokeAsync("VerificarFIELContribuyente", new object[] {
                        rfc}, this.VerificarFIELContribuyenteOperationCompleted, userState);
        }
        
        private void OnVerificarFIELContribuyenteOperationCompleted(object arg) {
            if ((this.VerificarFIELContribuyenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarFIELContribuyenteCompleted(this, new VerificarFIELContribuyenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCertificado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CertificateInfo ObtenerCertificado(string numeroSerie) {
            object[] results = this.Invoke("ObtenerCertificado", new object[] {
                        numeroSerie});
            return ((CertificateInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCertificadoAsync(string numeroSerie) {
            this.ObtenerCertificadoAsync(numeroSerie, null);
        }
        
        /// <remarks/>
        public void ObtenerCertificadoAsync(string numeroSerie, object userState) {
            if ((this.ObtenerCertificadoOperationCompleted == null)) {
                this.ObtenerCertificadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCertificadoOperationCompleted);
            }
            this.InvokeAsync("ObtenerCertificado", new object[] {
                        numeroSerie}, this.ObtenerCertificadoOperationCompleted, userState);
        }
        
        private void OnObtenerCertificadoOperationCompleted(object arg) {
            if ((this.ObtenerCertificadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCertificadoCompleted(this, new ObtenerCertificadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DesencriptarDeclaracion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DesencriptarDeclaracion(string nombreArchivo, string contenidoDocumento, int medioPresentacion, string rfcAutenticacion, string rfc) {
            object[] results = this.Invoke("DesencriptarDeclaracion", new object[] {
                        nombreArchivo,
                        contenidoDocumento,
                        medioPresentacion,
                        rfcAutenticacion,
                        rfc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DesencriptarDeclaracionAsync(string nombreArchivo, string contenidoDocumento, int medioPresentacion, string rfcAutenticacion, string rfc) {
            this.DesencriptarDeclaracionAsync(nombreArchivo, contenidoDocumento, medioPresentacion, rfcAutenticacion, rfc, null);
        }
        
        /// <remarks/>
        public void DesencriptarDeclaracionAsync(string nombreArchivo, string contenidoDocumento, int medioPresentacion, string rfcAutenticacion, string rfc, object userState) {
            if ((this.DesencriptarDeclaracionOperationCompleted == null)) {
                this.DesencriptarDeclaracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDesencriptarDeclaracionOperationCompleted);
            }
            this.InvokeAsync("DesencriptarDeclaracion", new object[] {
                        nombreArchivo,
                        contenidoDocumento,
                        medioPresentacion,
                        rfcAutenticacion,
                        rfc}, this.DesencriptarDeclaracionOperationCompleted, userState);
        }
        
        private void OnDesencriptarDeclaracionOperationCompleted(object arg) {
            if ((this.DesencriptarDeclaracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DesencriptarDeclaracionCompleted(this, new DesencriptarDeclaracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CertificateInfo {
        
        private CertificateType typeField;
        
        private CertificateState stateField;
        
        private string serialNumberField;
        
        private string taxPayerIDField;
        
        private string taxPayerNameField;
        
        private System.DateTime validityStartField;
        
        private System.DateTime validityEndField;
        
        /// <remarks/>
        public CertificateType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public CertificateState State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TaxPayerID {
            get {
                return this.taxPayerIDField;
            }
            set {
                this.taxPayerIDField = value;
            }
        }
        
        /// <remarks/>
        public string TaxPayerName {
            get {
                return this.taxPayerNameField;
            }
            set {
                this.taxPayerNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidityStart {
            get {
                return this.validityStartField;
            }
            set {
                this.validityStartField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidityEnd {
            get {
                return this.validityEndField;
            }
            set {
                this.validityEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum CertificateType {
        
        /// <remarks/>
        Any,
        
        /// <remarks/>
        ElectronicSignature,
        
        /// <remarks/>
        DigitalCertificate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum CertificateState {
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Revoked,
        
        /// <remarks/>
        Expired,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void EsFirmaValidaCompletedEventHandler(object sender, EsFirmaValidaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EsFirmaValidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EsFirmaValidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GenerarSelloDigitalCompletedEventHandler(object sender, GenerarSelloDigitalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarSelloDigitalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarSelloDigitalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void VerificarFIELContribuyenteCompletedEventHandler(object sender, VerificarFIELContribuyenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarFIELContribuyenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarFIELContribuyenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ObtenerCertificadoCompletedEventHandler(object sender, ObtenerCertificadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCertificadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCertificadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CertificateInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CertificateInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void DesencriptarDeclaracionCompletedEventHandler(object sender, DesencriptarDeclaracionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DesencriptarDeclaracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DesencriptarDeclaracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591