//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18052
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.1.
// 

namespace SAT.CreditosFiscales.Motor.Entidades.DatosProcesamiento
{
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class CreditosFiscalesSIAT
	{

		private CreditosFiscalesSIATDatosGenerales datosGeneralesField;

		private CreditosFiscalesSIATAgrupador[] agrupadoresField;

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public CreditosFiscalesSIATDatosGenerales DatosGenerales
		{
			get
			{
				return this.datosGeneralesField;
			}
			set
			{
				this.datosGeneralesField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Agrupador", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public CreditosFiscalesSIATAgrupador[] Agrupadores
		{
			get
			{
				return this.agrupadoresField;
			}
			set
			{
				this.agrupadoresField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesSIATDatosGenerales
	{

		private bool esSIATField;

		private string idPersonaField;

		private int idTipoLineaField;

		private CreditosFiscalesSIATDatosGeneralesConvenio convenioField;

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool EsSIAT
		{
			get
			{
				return this.esSIATField;
			}
			set
			{
				this.esSIATField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string IdPersona
		{
			get
			{
				return this.idPersonaField;
			}
			set
			{
				this.idPersonaField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int IdTipoLinea
		{
			get
			{
				return this.idTipoLineaField;
			}
			set
			{
				this.idTipoLineaField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public CreditosFiscalesSIATDatosGeneralesConvenio Convenio
		{
			get
			{
				return this.convenioField;
			}
			set
			{
				this.convenioField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesSIATDatosGeneralesConvenio
	{

		private string idConvenioField;

		private int tipoConvenioField;

		private bool tipoConvenioFieldSpecified;

		private string numeroConvenioField;

		private CreditosFiscalesSIATDatosGeneralesConvenioParcialidad parcialidadField;

		private long importeSaldoInsolutoInicialField;

		private bool importeSaldoInsolutoInicialFieldSpecified;

		private long importeSaldoInsolutoField;

		private bool importeSaldoInsolutoFieldSpecified;

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string IdConvenio
		{
			get
			{
				return this.idConvenioField;
			}
			set
			{
				this.idConvenioField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int TipoConvenio
		{
			get
			{
				return this.tipoConvenioField;
			}
			set
			{
				this.tipoConvenioField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool TipoConvenioSpecified
		{
			get
			{
				return this.tipoConvenioFieldSpecified;
			}
			set
			{
				this.tipoConvenioFieldSpecified = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string NumeroConvenio
		{
			get
			{
				return this.numeroConvenioField;
			}
			set
			{
				this.numeroConvenioField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public CreditosFiscalesSIATDatosGeneralesConvenioParcialidad Parcialidad
		{
			get
			{
				return this.parcialidadField;
			}
			set
			{
				this.parcialidadField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public long ImporteSaldoInsolutoInicial
		{
			get
			{
				return this.importeSaldoInsolutoInicialField;
			}
			set
			{
				this.importeSaldoInsolutoInicialField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ImporteSaldoInsolutoInicialSpecified
		{
			get
			{
				return this.importeSaldoInsolutoInicialFieldSpecified;
			}
			set
			{
				this.importeSaldoInsolutoInicialFieldSpecified = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public long ImporteSaldoInsoluto
		{
			get
			{
				return this.importeSaldoInsolutoField;
			}
			set
			{
				this.importeSaldoInsolutoField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ImporteSaldoInsolutoSpecified
		{
			get
			{
				return this.importeSaldoInsolutoFieldSpecified;
			}
			set
			{
				this.importeSaldoInsolutoFieldSpecified = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesSIATDatosGeneralesConvenioParcialidad
	{

		private int numeroParcialidadField;

		private bool numeroParcialidadFieldSpecified;

		private int totalDeParcialidadesField;

		private bool muestraTotalDeParcialidadesField;

		private string separadorField;

		private string descripcionParcialidadField;

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int NumeroParcialidad
		{
			get
			{
				return this.numeroParcialidadField;
			}
			set
			{
				this.numeroParcialidadField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool NumeroParcialidadSpecified
		{
			get
			{
				return this.numeroParcialidadFieldSpecified;
			}
			set
			{
				this.numeroParcialidadFieldSpecified = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int TotalDeParcialidades
		{
			get
			{
				return this.totalDeParcialidadesField;
			}
			set
			{
				this.totalDeParcialidadesField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool MuestraTotalDeParcialidades
		{
			get
			{
				return this.muestraTotalDeParcialidadesField;
			}
			set
			{
				this.muestraTotalDeParcialidadesField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Separador
		{
			get
			{
				return this.separadorField;
			}
			set
			{
				this.separadorField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string DescripcionParcialidad
		{
			get
			{
				return this.descripcionParcialidadField;
			}
			set
			{
				this.descripcionParcialidadField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesSIATAgrupador
	{

		private string idResolucionField;

		private CreditosFiscalesSIATAgrupadorConceptos[] conceptosOriginalField;

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string IdResolucion
		{
			get
			{
				return this.idResolucionField;
			}
			set
			{
				this.idResolucionField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Conceptos", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public CreditosFiscalesSIATAgrupadorConceptos[] ConceptosOriginal
		{
			get
			{
				return this.conceptosOriginalField;
			}
			set
			{
				this.conceptosOriginalField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class CreditosFiscalesSIATAgrupadorConceptos
	{

		private string idConceptoField;

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string IdConcepto
		{
			get
			{
				return this.idConceptoField;
			}
			set
			{
				this.idConceptoField = value;
			}
		}
	}
}