//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18052
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.CreditosFiscales.Motor.Negocio.RecepcionLC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudGeneracionLC", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun.Request")]
    [System.SerializableAttribute()]
    public partial class SolicitudGeneracionLC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.Concepto[] ConceptosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosGenerales DatosGeneralesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.Concepto[] Conceptos {
            get {
                return this.ConceptosField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptosField, value) != true)) {
                    this.ConceptosField = value;
                    this.RaisePropertyChanged("Conceptos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosGenerales DatosGenerales {
            get {
                return this.DatosGeneralesField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosGeneralesField, value) != true)) {
                    this.DatosGeneralesField = value;
                    this.RaisePropertyChanged("DatosGenerales");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosGenerales", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun.Request")]
    [System.SerializableAttribute()]
    public partial class DatosGenerales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveAlrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveGenericaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosIcep DatosIcepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionTipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaRecepcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdContribuyenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImporteTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosLineaCaptura[] LineasCapturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroConceptosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroParcialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrigenInformacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoComplementariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDeclaracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveAlr {
            get {
                return this.ClaveAlrField;
            }
            set {
                if ((this.ClaveAlrField.Equals(value) != true)) {
                    this.ClaveAlrField = value;
                    this.RaisePropertyChanged("ClaveAlr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveGenerica {
            get {
                return this.ClaveGenericaField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveGenericaField, value) != true)) {
                    this.ClaveGenericaField = value;
                    this.RaisePropertyChanged("ClaveGenerica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosIcep DatosIcep {
            get {
                return this.DatosIcepField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosIcepField, value) != true)) {
                    this.DatosIcepField = value;
                    this.RaisePropertyChanged("DatosIcep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTipoDocumento {
            get {
                return this.DescripcionTipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionTipoDocumentoField, value) != true)) {
                    this.DescripcionTipoDocumentoField = value;
                    this.RaisePropertyChanged("DescripcionTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaEmisionField, value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaRecepcion {
            get {
                return this.FechaRecepcionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaRecepcionField, value) != true)) {
                    this.FechaRecepcionField = value;
                    this.RaisePropertyChanged("FechaRecepcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdContribuyente {
            get {
                return this.IdContribuyenteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdContribuyenteField, value) != true)) {
                    this.IdContribuyenteField = value;
                    this.RaisePropertyChanged("IdContribuyente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDocumento {
            get {
                return this.IdDocumentoField;
            }
            set {
                if ((this.IdDocumentoField.Equals(value) != true)) {
                    this.IdDocumentoField = value;
                    this.RaisePropertyChanged("IdDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ImporteTotal {
            get {
                return this.ImporteTotalField;
            }
            set {
                if ((this.ImporteTotalField.Equals(value) != true)) {
                    this.ImporteTotalField = value;
                    this.RaisePropertyChanged("ImporteTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosLineaCaptura[] LineasCaptura {
            get {
                return this.LineasCapturaField;
            }
            set {
                if ((object.ReferenceEquals(this.LineasCapturaField, value) != true)) {
                    this.LineasCapturaField = value;
                    this.RaisePropertyChanged("LineasCaptura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroConceptos {
            get {
                return this.NumeroConceptosField;
            }
            set {
                if ((this.NumeroConceptosField.Equals(value) != true)) {
                    this.NumeroConceptosField = value;
                    this.RaisePropertyChanged("NumeroConceptos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> NumeroParcialidad {
            get {
                return this.NumeroParcialidadField;
            }
            set {
                if ((this.NumeroParcialidadField.Equals(value) != true)) {
                    this.NumeroParcialidadField = value;
                    this.RaisePropertyChanged("NumeroParcialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrigenInformacion {
            get {
                return this.OrigenInformacionField;
            }
            set {
                if ((this.OrigenInformacionField.Equals(value) != true)) {
                    this.OrigenInformacionField = value;
                    this.RaisePropertyChanged("OrigenInformacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoComplementaria {
            get {
                return this.TipoComplementariaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoComplementariaField, value) != true)) {
                    this.TipoComplementariaField = value;
                    this.RaisePropertyChanged("TipoComplementaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDeclaracion {
            get {
                return this.TipoDeclaracionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDeclaracionField, value) != true)) {
                    this.TipoDeclaracionField = value;
                    this.RaisePropertyChanged("TipoDeclaracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Concepto", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun.Request")]
    [System.SerializableAttribute()]
    public partial class Concepto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CantidadPagarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveGenericaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.Compensacion[] CompensacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosIcep DatosIcepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosLineaCaptura DatosLineaCapturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.Estimulo[] EstimulosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ImporteTotalAbonosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ImporteTotalCargosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroSecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.Transaccion[] TransaccionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> CantidadPagar {
            get {
                return this.CantidadPagarField;
            }
            set {
                if ((this.CantidadPagarField.Equals(value) != true)) {
                    this.CantidadPagarField = value;
                    this.RaisePropertyChanged("CantidadPagar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveGenerica {
            get {
                return this.ClaveGenericaField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveGenericaField, value) != true)) {
                    this.ClaveGenericaField = value;
                    this.RaisePropertyChanged("ClaveGenerica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.Compensacion[] Compensaciones {
            get {
                return this.CompensacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.CompensacionesField, value) != true)) {
                    this.CompensacionesField = value;
                    this.RaisePropertyChanged("Compensaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosIcep DatosIcep {
            get {
                return this.DatosIcepField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosIcepField, value) != true)) {
                    this.DatosIcepField = value;
                    this.RaisePropertyChanged("DatosIcep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosLineaCaptura DatosLineaCaptura {
            get {
                return this.DatosLineaCapturaField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosLineaCapturaField, value) != true)) {
                    this.DatosLineaCapturaField = value;
                    this.RaisePropertyChanged("DatosLineaCaptura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.Estimulo[] Estimulos {
            get {
                return this.EstimulosField;
            }
            set {
                if ((object.ReferenceEquals(this.EstimulosField, value) != true)) {
                    this.EstimulosField = value;
                    this.RaisePropertyChanged("Estimulos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> ImporteTotalAbonos {
            get {
                return this.ImporteTotalAbonosField;
            }
            set {
                if ((this.ImporteTotalAbonosField.Equals(value) != true)) {
                    this.ImporteTotalAbonosField = value;
                    this.RaisePropertyChanged("ImporteTotalAbonos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> ImporteTotalCargos {
            get {
                return this.ImporteTotalCargosField;
            }
            set {
                if ((this.ImporteTotalCargosField.Equals(value) != true)) {
                    this.ImporteTotalCargosField = value;
                    this.RaisePropertyChanged("ImporteTotalCargos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroSecuencia {
            get {
                return this.NumeroSecuenciaField;
            }
            set {
                if ((this.NumeroSecuenciaField.Equals(value) != true)) {
                    this.NumeroSecuenciaField = value;
                    this.RaisePropertyChanged("NumeroSecuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.Transaccion[] Transacciones {
            get {
                return this.TransaccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.TransaccionesField, value) != true)) {
                    this.TransaccionesField = value;
                    this.RaisePropertyChanged("Transacciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosIcep", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun.Request")]
    [System.SerializableAttribute()]
    public partial class DatosIcep : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClavePeriodicidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClavePeriodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionPeriodicidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionPeriodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EjercicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCausacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IcepCorrectoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClavePeriodicidad {
            get {
                return this.ClavePeriodicidadField;
            }
            set {
                if ((object.ReferenceEquals(this.ClavePeriodicidadField, value) != true)) {
                    this.ClavePeriodicidadField = value;
                    this.RaisePropertyChanged("ClavePeriodicidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClavePeriodo {
            get {
                return this.ClavePeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClavePeriodoField, value) != true)) {
                    this.ClavePeriodoField = value;
                    this.RaisePropertyChanged("ClavePeriodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionPeriodicidad {
            get {
                return this.DescripcionPeriodicidadField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionPeriodicidadField, value) != true)) {
                    this.DescripcionPeriodicidadField = value;
                    this.RaisePropertyChanged("DescripcionPeriodicidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionPeriodo {
            get {
                return this.DescripcionPeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionPeriodoField, value) != true)) {
                    this.DescripcionPeriodoField = value;
                    this.RaisePropertyChanged("DescripcionPeriodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ejercicio {
            get {
                return this.EjercicioField;
            }
            set {
                if ((object.ReferenceEquals(this.EjercicioField, value) != true)) {
                    this.EjercicioField = value;
                    this.RaisePropertyChanged("Ejercicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCausacion {
            get {
                return this.FechaCausacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCausacionField, value) != true)) {
                    this.FechaCausacionField = value;
                    this.RaisePropertyChanged("FechaCausacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> IcepCorrecto {
            get {
                return this.IcepCorrectoField;
            }
            set {
                if ((this.IcepCorrectoField.Equals(value) != true)) {
                    this.IcepCorrectoField = value;
                    this.RaisePropertyChanged("IcepCorrecto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosLineaCaptura", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun")]
    [System.SerializableAttribute()]
    public partial class DatosLineaCaptura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaVigenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineaCapturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PagoObligadoInternetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaVigencia {
            get {
                return this.FechaVigenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaVigenciaField, value) != true)) {
                    this.FechaVigenciaField = value;
                    this.RaisePropertyChanged("FechaVigencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineaCaptura {
            get {
                return this.LineaCapturaField;
            }
            set {
                if ((object.ReferenceEquals(this.LineaCapturaField, value) != true)) {
                    this.LineaCapturaField = value;
                    this.RaisePropertyChanged("LineaCaptura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PagoObligadoInternet {
            get {
                return this.PagoObligadoInternetField;
            }
            set {
                if ((this.PagoObligadoInternetField.Equals(value) != true)) {
                    this.PagoObligadoInternetField = value;
                    this.RaisePropertyChanged("PagoObligadoInternet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compensacion", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun.Request")]
    [System.SerializableAttribute()]
    public partial class Compensacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> EjercicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCausacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaDeclaSaldoFavorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCompensacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdConceptoOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPeriodicidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPeriodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTipoCompensacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTipoDeclaracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumOperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumOperacion2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RemanenteActualizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RemanenteHistoricoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SaldoAplicarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SaldoFavorOrigenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<short> Ejercicio {
            get {
                return this.EjercicioField;
            }
            set {
                if ((this.EjercicioField.Equals(value) != true)) {
                    this.EjercicioField = value;
                    this.RaisePropertyChanged("Ejercicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FechaCausacion {
            get {
                return this.FechaCausacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCausacionField, value) != true)) {
                    this.FechaCausacionField = value;
                    this.RaisePropertyChanged("FechaCausacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FechaDeclaSaldoFavor {
            get {
                return this.FechaDeclaSaldoFavorField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaDeclaSaldoFavorField, value) != true)) {
                    this.FechaDeclaSaldoFavorField = value;
                    this.RaisePropertyChanged("FechaDeclaSaldoFavor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> IdCompensacion {
            get {
                return this.IdCompensacionField;
            }
            set {
                if ((this.IdCompensacionField.Equals(value) != true)) {
                    this.IdCompensacionField = value;
                    this.RaisePropertyChanged("IdCompensacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdConceptoOrigen {
            get {
                return this.IdConceptoOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.IdConceptoOrigenField, value) != true)) {
                    this.IdConceptoOrigenField = value;
                    this.RaisePropertyChanged("IdConceptoOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdPeriodicidad {
            get {
                return this.IdPeriodicidadField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPeriodicidadField, value) != true)) {
                    this.IdPeriodicidadField = value;
                    this.RaisePropertyChanged("IdPeriodicidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPeriodo {
            get {
                return this.IdPeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPeriodoField, value) != true)) {
                    this.IdPeriodoField = value;
                    this.RaisePropertyChanged("IdPeriodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdTipoCompensacion {
            get {
                return this.IdTipoCompensacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTipoCompensacionField, value) != true)) {
                    this.IdTipoCompensacionField = value;
                    this.RaisePropertyChanged("IdTipoCompensacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdTipoDeclaracion {
            get {
                return this.IdTipoDeclaracionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTipoDeclaracionField, value) != true)) {
                    this.IdTipoDeclaracionField = value;
                    this.RaisePropertyChanged("IdTipoDeclaracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumOperacion {
            get {
                return this.NumOperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumOperacionField, value) != true)) {
                    this.NumOperacionField = value;
                    this.RaisePropertyChanged("NumOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumOperacion2 {
            get {
                return this.NumOperacion2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NumOperacion2Field, value) != true)) {
                    this.NumOperacion2Field = value;
                    this.RaisePropertyChanged("NumOperacion2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> RemanenteActualizado {
            get {
                return this.RemanenteActualizadoField;
            }
            set {
                if ((this.RemanenteActualizadoField.Equals(value) != true)) {
                    this.RemanenteActualizadoField = value;
                    this.RaisePropertyChanged("RemanenteActualizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> RemanenteHistorico {
            get {
                return this.RemanenteHistoricoField;
            }
            set {
                if ((this.RemanenteHistoricoField.Equals(value) != true)) {
                    this.RemanenteHistoricoField = value;
                    this.RaisePropertyChanged("RemanenteHistorico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> SaldoAplicar {
            get {
                return this.SaldoAplicarField;
            }
            set {
                if ((this.SaldoAplicarField.Equals(value) != true)) {
                    this.SaldoAplicarField = value;
                    this.RaisePropertyChanged("SaldoAplicar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> SaldoFavorOrigen {
            get {
                return this.SaldoFavorOrigenField;
            }
            set {
                if ((this.SaldoFavorOrigenField.Equals(value) != true)) {
                    this.SaldoFavorOrigenField = value;
                    this.RaisePropertyChanged("SaldoFavorOrigen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estimulo", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun.Request")]
    [System.SerializableAttribute()]
    public partial class Estimulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdEstimuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEstimulo {
            get {
                return this.IdEstimuloField;
            }
            set {
                if ((object.ReferenceEquals(this.IdEstimuloField, value) != true)) {
                    this.IdEstimuloField = value;
                    this.RaisePropertyChanged("IdEstimulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaccion", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun.Request")]
    [System.SerializableAttribute()]
    public partial class Transaccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaGeneracionLC", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun.Response")]
    [System.SerializableAttribute()]
    public partial class RespuestaGeneracionLC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.RespuestaConcepto[] RespuestaConceptosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.RespuestaDatosGenerales RespuestaDatosGeneralesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.RespuestaError[] RespuestaErroresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.RespuestaConcepto[] RespuestaConceptos {
            get {
                return this.RespuestaConceptosField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaConceptosField, value) != true)) {
                    this.RespuestaConceptosField = value;
                    this.RaisePropertyChanged("RespuestaConceptos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.RespuestaDatosGenerales RespuestaDatosGenerales {
            get {
                return this.RespuestaDatosGeneralesField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaDatosGeneralesField, value) != true)) {
                    this.RespuestaDatosGeneralesField = value;
                    this.RaisePropertyChanged("RespuestaDatosGenerales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.RespuestaError[] RespuestaErrores {
            get {
                return this.RespuestaErroresField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaErroresField, value) != true)) {
                    this.RespuestaErroresField = value;
                    this.RaisePropertyChanged("RespuestaErrores");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaDatosGenerales", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun.Response")]
    [System.SerializableAttribute()]
    public partial class RespuestaDatosGenerales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosLineaCaptura[] LineasCapturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.RespuestaResultado ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SolicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosLineaCaptura[] LineasCaptura {
            get {
                return this.LineasCapturaField;
            }
            set {
                if ((object.ReferenceEquals(this.LineasCapturaField, value) != true)) {
                    this.LineasCapturaField = value;
                    this.RaisePropertyChanged("LineasCaptura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.RespuestaResultado Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConcepto", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun.Response")]
    [System.SerializableAttribute()]
    public partial class RespuestaConcepto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosLineaCaptura DatosLineaCapturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroSecuenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.DatosLineaCaptura DatosLineaCaptura {
            get {
                return this.DatosLineaCapturaField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosLineaCapturaField, value) != true)) {
                    this.DatosLineaCapturaField = value;
                    this.RaisePropertyChanged("DatosLineaCaptura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroSecuencia {
            get {
                return this.NumeroSecuenciaField;
            }
            set {
                if ((this.NumeroSecuenciaField.Equals(value) != true)) {
                    this.NumeroSecuenciaField = value;
                    this.RaisePropertyChanged("NumeroSecuencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaError", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun.Response")]
    [System.SerializableAttribute()]
    public partial class RespuestaError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaResultado", Namespace="http://schemas.datacontract.org/2004/07/Sat.DyP.Sispr.Modelo.Comun.Response")]
    public enum RespuestaResultado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aceptado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rechazado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorPlataforma = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Sat.DyP.Sispr", ConfigurationName="RecepcionLC.IRecepcion")]
    public interface IRecepcion {
        
        [System.ServiceModel.OperationContractAttribute(Action="Sat.DyP.Sispr/IRecepcion/GenerarLineaCaptura", ReplyAction="Sat.DyP.Sispr/IRecepcion/GenerarLineaCapturaResponse")]
        SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.RespuestaGeneracionLC GenerarLineaCaptura(SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.SolicitudGeneracionLC solicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecepcionChannel : SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.IRecepcion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecepcionClient : System.ServiceModel.ClientBase<SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.IRecepcion>, SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.IRecepcion {
        
        public RecepcionClient() {
        }
        
        public RecepcionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecepcionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.RespuestaGeneracionLC GenerarLineaCaptura(SAT.CreditosFiscales.Motor.Negocio.RecepcionLC.SolicitudGeneracionLC solicitud) {
            return base.Channel.GenerarLineaCaptura(solicitud);
        }
    }
}
