//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargaDeCatalogos.CatalogosDyP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoFiltro", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
        ".Interfaces.Filtros")]
    [System.SerializableAttribute()]
    public partial class CatalogoFiltro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CargaDeCatalogos.CatalogosDyP.Alr AlrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CargaDeCatalogos.CatalogosDyP.ConceptoPago ConceptoPagoField;
        
        private int IdOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CargaDeCatalogos.CatalogosDyP.Periodicidad PeriodicidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CargaDeCatalogos.CatalogosDyP.TipoDocumento TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CargaDeCatalogos.CatalogosDyP.Transaccion TransaccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CargaDeCatalogos.CatalogosDyP.Alr Alr {
            get {
                return this.AlrField;
            }
            set {
                if ((object.ReferenceEquals(this.AlrField, value) != true)) {
                    this.AlrField = value;
                    this.RaisePropertyChanged("Alr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CargaDeCatalogos.CatalogosDyP.ConceptoPago ConceptoPago {
            get {
                return this.ConceptoPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptoPagoField, value) != true)) {
                    this.ConceptoPagoField = value;
                    this.RaisePropertyChanged("ConceptoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdOrigen {
            get {
                return this.IdOrigenField;
            }
            set {
                if ((this.IdOrigenField.Equals(value) != true)) {
                    this.IdOrigenField = value;
                    this.RaisePropertyChanged("IdOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CargaDeCatalogos.CatalogosDyP.Periodicidad Periodicidad {
            get {
                return this.PeriodicidadField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodicidadField, value) != true)) {
                    this.PeriodicidadField = value;
                    this.RaisePropertyChanged("Periodicidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CargaDeCatalogos.CatalogosDyP.TipoDocumento TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CargaDeCatalogos.CatalogosDyP.Transaccion Transaccion {
            get {
                return this.TransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.TransaccionField, value) != true)) {
                    this.TransaccionField = value;
                    this.RaisePropertyChanged("Transaccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alr", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
        ".Interfaces.Entidades")]
    [System.SerializableAttribute()]
    public partial class Alr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdAlrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdAlr {
            get {
                return this.IdAlrField;
            }
            set {
                if ((object.ReferenceEquals(this.IdAlrField, value) != true)) {
                    this.IdAlrField = value;
                    this.RaisePropertyChanged("IdAlr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConceptoPago", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
        ".Interfaces.Entidades")]
    [System.SerializableAttribute()]
    public partial class ConceptoPago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdConceptoPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdConceptoPago {
            get {
                return this.IdConceptoPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdConceptoPagoField, value) != true)) {
                    this.IdConceptoPagoField = value;
                    this.RaisePropertyChanged("IdConceptoPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Periodicidad", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
        ".Interfaces.Entidades")]
    [System.SerializableAttribute()]
    public partial class Periodicidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPeriodicidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPeriodicidad {
            get {
                return this.IdPeriodicidadField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPeriodicidadField, value) != true)) {
                    this.IdPeriodicidadField = value;
                    this.RaisePropertyChanged("IdPeriodicidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDocumento", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
        ".Interfaces.Entidades")]
    [System.SerializableAttribute()]
    public partial class TipoDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoDocumento {
            get {
                return this.IdTipoDocumentoField;
            }
            set {
                if ((this.IdTipoDocumentoField.Equals(value) != true)) {
                    this.IdTipoDocumentoField = value;
                    this.RaisePropertyChanged("IdTipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaccion", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
        ".Interfaces.Entidades")]
    [System.SerializableAttribute()]
    public partial class Transaccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CargaDeCatalogos.CatalogosDyP.TipoTransaccion TipoTransaccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdTransaccion {
            get {
                return this.IdTransaccionField;
            }
            set {
                if ((this.IdTransaccionField.Equals(value) != true)) {
                    this.IdTransaccionField = value;
                    this.RaisePropertyChanged("IdTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CargaDeCatalogos.CatalogosDyP.TipoTransaccion TipoTransaccion {
            get {
                return this.TipoTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTransaccionField, value) != true)) {
                    this.TipoTransaccionField = value;
                    this.RaisePropertyChanged("TipoTransaccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTransaccion", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
        ".Interfaces.Entidades")]
    [System.SerializableAttribute()]
    public partial class TipoTransaccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoTransaccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoTransaccion {
            get {
                return this.IdTipoTransaccionField;
            }
            set {
                if ((this.IdTipoTransaccionField.Equals(value) != true)) {
                    this.IdTipoTransaccionField = value;
                    this.RaisePropertyChanged("IdTipoTransaccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Periodo", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
        ".Interfaces.Entidades")]
    [System.SerializableAttribute()]
    public partial class Periodo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdMesFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdMesInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPeriodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CargaDeCatalogos.CatalogosDyP.Periodicidad PeriodicidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdMesFinal {
            get {
                return this.IdMesFinalField;
            }
            set {
                if ((this.IdMesFinalField.Equals(value) != true)) {
                    this.IdMesFinalField = value;
                    this.RaisePropertyChanged("IdMesFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdMesInicial {
            get {
                return this.IdMesInicialField;
            }
            set {
                if ((this.IdMesInicialField.Equals(value) != true)) {
                    this.IdMesInicialField = value;
                    this.RaisePropertyChanged("IdMesInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPeriodo {
            get {
                return this.IdPeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPeriodoField, value) != true)) {
                    this.IdPeriodoField = value;
                    this.RaisePropertyChanged("IdPeriodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MesFinal {
            get {
                return this.MesFinalField;
            }
            set {
                if ((object.ReferenceEquals(this.MesFinalField, value) != true)) {
                    this.MesFinalField = value;
                    this.RaisePropertyChanged("MesFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MesInicial {
            get {
                return this.MesInicialField;
            }
            set {
                if ((object.ReferenceEquals(this.MesInicialField, value) != true)) {
                    this.MesInicialField = value;
                    this.RaisePropertyChanged("MesInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CargaDeCatalogos.CatalogosDyP.Periodicidad Periodicidad {
            get {
                return this.PeriodicidadField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodicidadField, value) != true)) {
                    this.PeriodicidadField = value;
                    this.RaisePropertyChanged("Periodicidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoErrorNegocio", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
        ".Interfaces.Excepciones")]
    [System.SerializableAttribute()]
    public partial class CatalogoErrorNegocio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatalogosDyP.IConsultaCatalogos")]
    public interface IConsultaCatalogos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarPeriodos", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarPeriodosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CargaDeCatalogos.CatalogosDyP.CatalogoErrorNegocio), Action="http://tempuri.org/IConsultaCatalogos/ConsultarPeriodosCatalogoErrorNegocioFault", Name="CatalogoErrorNegocio", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
            ".Interfaces.Excepciones")]
        CargaDeCatalogos.CatalogosDyP.Periodo[] ConsultarPeriodos(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarPeriodos", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarPeriodosResponse")]
        System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.Periodo[]> ConsultarPeriodosAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarPeriodicidades", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarPeriodicidadesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CargaDeCatalogos.CatalogosDyP.CatalogoErrorNegocio), Action="http://tempuri.org/IConsultaCatalogos/ConsultarPeriodicidadesCatalogoErrorNegocio" +
            "Fault", Name="CatalogoErrorNegocio", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
            ".Interfaces.Excepciones")]
        CargaDeCatalogos.CatalogosDyP.Periodicidad[] ConsultarPeriodicidades(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarPeriodicidades", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarPeriodicidadesResponse")]
        System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.Periodicidad[]> ConsultarPeriodicidadesAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarTiposDocumentos", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarTiposDocumentosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CargaDeCatalogos.CatalogosDyP.CatalogoErrorNegocio), Action="http://tempuri.org/IConsultaCatalogos/ConsultarTiposDocumentosCatalogoErrorNegoci" +
            "oFault", Name="CatalogoErrorNegocio", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
            ".Interfaces.Excepciones")]
        CargaDeCatalogos.CatalogosDyP.TipoDocumento[] ConsultarTiposDocumentos(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarTiposDocumentos", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarTiposDocumentosResponse")]
        System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.TipoDocumento[]> ConsultarTiposDocumentosAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarTransacciones", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarTransaccionesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CargaDeCatalogos.CatalogosDyP.CatalogoErrorNegocio), Action="http://tempuri.org/IConsultaCatalogos/ConsultarTransaccionesCatalogoErrorNegocioF" +
            "ault", Name="CatalogoErrorNegocio", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
            ".Interfaces.Excepciones")]
        CargaDeCatalogos.CatalogosDyP.Transaccion[] ConsultarTransacciones(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarTransacciones", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarTransaccionesResponse")]
        System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.Transaccion[]> ConsultarTransaccionesAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarTransaccionesXTipoDocumento", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarTransaccionesXTipoDocumentoRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(CargaDeCatalogos.CatalogosDyP.CatalogoErrorNegocio), Action="http://tempuri.org/IConsultaCatalogos/ConsultarTransaccionesXTipoDocumentoCatalog" +
            "oErrorNegocioFault", Name="CatalogoErrorNegocio", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
            ".Interfaces.Excepciones")]
        CargaDeCatalogos.CatalogosDyP.Transaccion[] ConsultarTransaccionesXTipoDocumento(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarTransaccionesXTipoDocumento", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarTransaccionesXTipoDocumentoRespons" +
            "e")]
        System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.Transaccion[]> ConsultarTransaccionesXTipoDocumentoAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarConceptosPagos", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarConceptosPagosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CargaDeCatalogos.CatalogosDyP.CatalogoErrorNegocio), Action="http://tempuri.org/IConsultaCatalogos/ConsultarConceptosPagosCatalogoErrorNegocio" +
            "Fault", Name="CatalogoErrorNegocio", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
            ".Interfaces.Excepciones")]
        CargaDeCatalogos.CatalogosDyP.ConceptoPago[] ConsultarConceptosPagos(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarConceptosPagos", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarConceptosPagosResponse")]
        System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.ConceptoPago[]> ConsultarConceptosPagosAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarAlrs", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarAlrsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CargaDeCatalogos.CatalogosDyP.CatalogoErrorNegocio), Action="http://tempuri.org/IConsultaCatalogos/ConsultarAlrsCatalogoErrorNegocioFault", Name="CatalogoErrorNegocio", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
            ".Interfaces.Excepciones")]
        CargaDeCatalogos.CatalogosDyP.Alr[] ConsultarAlrs(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarAlrs", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarAlrsResponse")]
        System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.Alr[]> ConsultarAlrsAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarOrigen", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarOrigenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CargaDeCatalogos.CatalogosDyP.CatalogoErrorNegocio), Action="http://tempuri.org/IConsultaCatalogos/ConsultarOrigenCatalogoErrorNegocioFault", Name="CatalogoErrorNegocio", Namespace="http://schemas.datacontract.org/2004/07/Sat.Scade.Sispr.Servicios.CatalogosOrigen" +
            ".Interfaces.Excepciones")]
        string ConsultarOrigen(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaCatalogos/ConsultarOrigen", ReplyAction="http://tempuri.org/IConsultaCatalogos/ConsultarOrigenResponse")]
        System.Threading.Tasks.Task<string> ConsultarOrigenAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultaCatalogosChannel : CargaDeCatalogos.CatalogosDyP.IConsultaCatalogos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaCatalogosClient : System.ServiceModel.ClientBase<CargaDeCatalogos.CatalogosDyP.IConsultaCatalogos>, CargaDeCatalogos.CatalogosDyP.IConsultaCatalogos {
        
        public ConsultaCatalogosClient() {
        }
        
        public ConsultaCatalogosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaCatalogosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaCatalogosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaCatalogosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CargaDeCatalogos.CatalogosDyP.Periodo[] ConsultarPeriodos(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarPeriodos(filtro);
        }
        
        public System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.Periodo[]> ConsultarPeriodosAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarPeriodosAsync(filtro);
        }
        
        public CargaDeCatalogos.CatalogosDyP.Periodicidad[] ConsultarPeriodicidades(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarPeriodicidades(filtro);
        }
        
        public System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.Periodicidad[]> ConsultarPeriodicidadesAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarPeriodicidadesAsync(filtro);
        }
        
        public CargaDeCatalogos.CatalogosDyP.TipoDocumento[] ConsultarTiposDocumentos(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarTiposDocumentos(filtro);
        }
        
        public System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.TipoDocumento[]> ConsultarTiposDocumentosAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarTiposDocumentosAsync(filtro);
        }
        
        public CargaDeCatalogos.CatalogosDyP.Transaccion[] ConsultarTransacciones(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarTransacciones(filtro);
        }
        
        public System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.Transaccion[]> ConsultarTransaccionesAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarTransaccionesAsync(filtro);
        }
        
        public CargaDeCatalogos.CatalogosDyP.Transaccion[] ConsultarTransaccionesXTipoDocumento(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarTransaccionesXTipoDocumento(filtro);
        }
        
        public System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.Transaccion[]> ConsultarTransaccionesXTipoDocumentoAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarTransaccionesXTipoDocumentoAsync(filtro);
        }
        
        public CargaDeCatalogos.CatalogosDyP.ConceptoPago[] ConsultarConceptosPagos(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarConceptosPagos(filtro);
        }
        
        public System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.ConceptoPago[]> ConsultarConceptosPagosAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarConceptosPagosAsync(filtro);
        }
        
        public CargaDeCatalogos.CatalogosDyP.Alr[] ConsultarAlrs(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarAlrs(filtro);
        }
        
        public System.Threading.Tasks.Task<CargaDeCatalogos.CatalogosDyP.Alr[]> ConsultarAlrsAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarAlrsAsync(filtro);
        }
        
        public string ConsultarOrigen(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarOrigen(filtro);
        }
        
        public System.Threading.Tasks.Task<string> ConsultarOrigenAsync(CargaDeCatalogos.CatalogosDyP.CatalogoFiltro filtro) {
            return base.Channel.ConsultarOrigenAsync(filtro);
        }
    }
}
