//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sat.CreditosFiscales.Procesamiento.LogicaNegocio.ServicioImpresionLC {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumTemplate", Namespace="http://schemas.datacontract.org/2004/07/Sat.CreditosFiscales.Impresion.Entidades")]
    public enum EnumTemplate : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormatoParaPagoTotal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConfirmacionDeMovimientosContables = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConfirmacionDeTransacciones = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioImpresionLC.IServicioGeneraFormato")]
    public interface IServicioGeneraFormato {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneraFormato/GeneraArchivo", ReplyAction="http://tempuri.org/IServicioGeneraFormato/GeneraArchivoResponse")]
        byte[] GeneraArchivo(Sat.CreditosFiscales.Procesamiento.LogicaNegocio.ServicioImpresionLC.EnumTemplate template, System.Collections.Generic.List<string> listaDeFolios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneraFormato/GeneraXML", ReplyAction="http://tempuri.org/IServicioGeneraFormato/GeneraXMLResponse")]
        string GeneraXML(Sat.CreditosFiscales.Procesamiento.LogicaNegocio.ServicioImpresionLC.EnumTemplate template, System.Collections.Generic.List<string> listaDeFolios);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioGeneraFormatoChannel : Sat.CreditosFiscales.Procesamiento.LogicaNegocio.ServicioImpresionLC.IServicioGeneraFormato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGeneraFormatoClient : System.ServiceModel.ClientBase<Sat.CreditosFiscales.Procesamiento.LogicaNegocio.ServicioImpresionLC.IServicioGeneraFormato>, Sat.CreditosFiscales.Procesamiento.LogicaNegocio.ServicioImpresionLC.IServicioGeneraFormato {
        
        public ServicioGeneraFormatoClient() {
        }
        
        public ServicioGeneraFormatoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGeneraFormatoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGeneraFormatoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGeneraFormatoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GeneraArchivo(Sat.CreditosFiscales.Procesamiento.LogicaNegocio.ServicioImpresionLC.EnumTemplate template, System.Collections.Generic.List<string> listaDeFolios) {
            return base.Channel.GeneraArchivo(template, listaDeFolios);
        }
        
        public string GeneraXML(Sat.CreditosFiscales.Procesamiento.LogicaNegocio.ServicioImpresionLC.EnumTemplate template, System.Collections.Generic.List<string> listaDeFolios) {
            return base.Channel.GeneraXML(template, listaDeFolios);
        }
    }
}
