//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sat.CreditosFiscales.Presentacion.Portal.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicioLog")]
    public interface IServicioLog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLog/EscribirEntradaLog", ReplyAction="http://tempuri.org/IServicioLog/EscribirEntradaLogResponse")]
        void EscribirEntradaLog(int eventoID, string mensaje, System.Diagnostics.EventLogEntryType eventoLogTipo, string aplicacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioLogChannel : Sat.CreditosFiscales.Presentacion.Portal.ServiceReference1.IServicioLog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioLogClient : System.ServiceModel.ClientBase<Sat.CreditosFiscales.Presentacion.Portal.ServiceReference1.IServicioLog>, Sat.CreditosFiscales.Presentacion.Portal.ServiceReference1.IServicioLog {
        
        public ServicioLogClient() {
        }
        
        public ServicioLogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioLogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EscribirEntradaLog(int eventoID, string mensaje, System.Diagnostics.EventLogEntryType eventoLogTipo, string aplicacion) {
            base.Channel.EscribirEntradaLog(eventoID, mensaje, eventoLogTipo, aplicacion);
        }
    }
}
