USE [MotorTraductor];
BEGIN TRAN

INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(307186	,'DER / VISITANTE SIN PERMISO PARA REALIZAR ACTIVIDADES REMUNERADAS SIN FINES TURISTICOS (ART. 8, FRACC. I DE LA LFD).',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(0901	,'IH/ IMPUESTO POR LA ACTIVIDAD DE EXPLORACIÓN Y EXTRACCIÓN DE HIDROCARBUROS',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(506158	,'APROV/ MULTAS PREVISTAS EN EL ART. 160 DE LA LEY NACIONAL DE EJECUCIÓN PENAL',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(50547	,'APROV/ MULTAS IMPUESTAS POR LA OMISIÓN EN EL CUMPLIMIENTO DE LOS ARTÍCULOS 17 Y 18 DE LA LEY FEDERAL PARA LA PREVENCIÓN E IDENTIFICACIÓN DE OPERACIONES CON RECURSOS DE PROCEDENCIA ILÍCITA',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(0442	,'IEPS/ OTROS, GASOLINA (IMPORTACIÓN DE GASOLINA)',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(0443	,'IEPS/ PEMEX, DIÉSEL(IMPORTACIÓN DE DIÉSEL)',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(0444	,'IEPS/ OTROS, DIÉSEL (IMPORTACIÓN DE DIÉSEL)',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(0445	,'IEPS/ IMPORTACIÓN DE COMBUSTIBLES NO FÓSILES  ',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(0446	,'IEPS/ IMPUESTO ESPECIAL SOBRE PRODUCCIÓN Y SERVICIOS (IMPUESTOS NO COMPRENDIDOS EN LA LEY DE INGRESOS VIGENTE, CAUSADOS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN)',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(0168	,'ISR/ ISR RÉGIMEN SIMPLIFICADO DE CONFIANZA, PERSONAS FÍSICAS ',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(0167	,'ISR/ ISR RÉGIMEN SIMPLIFICADO DE CONFIANZA, PERSONAS MORALES ',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(0318	,'IVA/ IVA RÉGIMEN SIMPLIFICADO DE CONFIANZA',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(308126	,'DER/ SECRETARIA DE SALUD.',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(308127	,'DER/ SECRETARIA DE SEGURIDAD Y PROTECCION CIUDADANA.',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(308128	,'DER/ SECRETARIA DEL BIENESTAR.',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(308129	,'DER/ POR LA OBTENCION DE CODIGOS DE SEGURIDAD QUE SE IMPRIMAN EN LAS CAJETILLAS, ESTUCHES, EMPAQUES, ENVOLTURAS O CUALQUIER OTRO OBJETO QUE CONTENGA CIGARROS U OTROS TABACOS LABRADOS PARA VENTA EN MEXICO (ART.  53-I  DE LA LFD).',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(308130	,'DER/DER/POR LA OBTENCION DE FOLIOS ELECTRONICOS PARA LA IMPRESION DE MARBETES ELECTRONICOS QUE SE ADHIERAN A LOS ENVASES QUE CONTENGAN BEBIDAS ALCOHOLICAS A QUE SE REFIERE LA LEY DEL IMPUESTO ESPECIAL SOBRE PRODUCCION Y SERVICIOS (ART. 53-K, FRACCIÓN II DE LA LFD).',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(308131	,'DER/DERECHOS DEROGADOS DE LA FISCALIA GENERAL DE LA REPUBLICA.',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(308132	,'DER/ DERECHO POR AUTORIZACION DE ARRIBO, DESPACHO, MANIOBRA DE FONDEO O ENMIENDA (ART. 170 DE LA LFD).',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(308133	,'DER/ POR EL DERECHO DE CUMPLIMIENTO DEL CODIGO INTERNACIONAL PARA LA PROTECCION DE LOS BUQUES Y DE LAS INSTALACIONES PORTUARIAS (ART. 170-G DE LA LFD).',1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoDyP] ([ConceptoDyP],[Descripcion],[Activo]) VALUES(308134	,'DER / DERECHOS DEROGADOS DE LA SECRETARIA DE COMUNICACIONES Y TRANSPORTES, MEDIANTE EL DECRETO DEL 7 DE DICIEMBRE DE 2020.',1);

INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,400236,'DERECHO DE VISITANTE SIN PERMISO PARA REALIZAR ACTIVIDADES REMUNERADAS CON FINES TURÍSTICOS (DNR-T)',307182,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,400249,'DERECHO DE VISITANTE SIN PERMISO PARA REALIZAR ACTIVIDADES REMUNERADAS SIN FINES TURÍSTICOS (DNR-O)',307186,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,180003,'IMPUESTO POR LA ACTIVIDAD DE EXPLORACIÓN Y EXTRACCIÓN DE HIDROCARBUROS',0901,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,700193,'MULTAS PREVISTAS EN EL ART. 160 DE LA LEY NACIONAL DE EJECUCIÓN PENAL',506158,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,700194,'MULTAS IMPUESTAS POR LA OMISIÓN EN EL CUMPLIMIENTO DE LOS ARTÍCULOS 17 Y 18 DE LA LEY FEDERAL PARA LA PREVENCIÓN E IDENTIFICACIÓN DE OPERACIONES CON RECURSOS DE PROCEDENCIA ILÍCITA',50547,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,140042,'OTROS, GASOLINA (IMPORTACIÓN DE GASOLINA)',0442,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,140043,'PEMEX, DIÉSEL(IMPORTACIÓN DE DIÉSEL)',0443,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,140044,'OTROS, DIÉSEL (IMPORTACIÓN DE DIÉSEL)',0444,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,140045,'IMPORTACIÓN DE COMBUSTIBLES NO FÓSILES ',0445,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,500155,'IMPUESTO ESPECIAL SOBRE PRODUCCIÓN Y SERVICIOS (IMPUESTOS NO COMPRENDIDOS EN LA LEY DE INGRESOS VIGENTE, CAUSADOS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN)',0446,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,110081,'ISR RÉGIMEN SIMPLIFICADO DE CONFIANZA, PERSONAS FÍSICAS',0168,1)
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,110083,'ISR RÉGIMEN SIMPLIFICADO DE CONFIANZA, PERSONAS MORALES',0167,1)
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,130023,'IVA RÉGIMEN SIMPLIFICADO DE CONFIANZA',0318,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,400295,'SECRETARIA DE SALUD.',308126,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,400296,'SECRETARIA DE SEGURIDAD Y PROTECCION CIUDADANA.',308127,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,400297,'SECRETARIA DEL BIENESTAR.',308128,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,400298,'POR LA OBTENCION DE CODIGOS DE SEGURIDAD QUE SE IMPRIMAN EN LAS CAJETILLAS, ESTUCHES, EMPAQUES, ENVOLTURAS O CUALQUIER OTRO OBJETO QUE CONTENGA CIGARROS U OTROS TABACOS LABRADOS PARA VENTA EN MEXICO (ART.  53-I  DE LA LFD).',308129,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,400299,'POR LA OBTENCION DE FOLIOS ELECTRONICOS PARA LA IMPRESION DE MARBETES ELECTRONICOS QUE SE ADHIERAN A LOS ENVASES QUE CONTENGAN BEBIDAS ALCOHOLICAS A QUE SE REFIERE LA LEY DEL IMPUESTO ESPECIAL SOBRE PRODUCCION Y SERVICIOS (ART. 53-K, FRACCIÓN II DE LA LFD).',308130,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,500165,'DERECHOS DEROGADOS DE LA FISCALIA GENERAL DE LA REPUBLICA.',308131,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,500166,'DERECHO POR AUTORIZACION DE ARRIBO, DESPACHO, MANIOBRA DE FONDEO O ENMIENDA (ART. 170 DE LA LFD).',308132,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,500167,'POR EL DERECHO DE CUMPLIMIENTO DEL CODIGO INTERNACIONAL PARA LA PROTECCION DE LOS BUQUES Y DE LAS INSTALACIONES PORTUARIAS (ART. 170-G DE LA LFD).',308133,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(3,500168,'DERECHOS DEROGADOS DE LA SECRETARIA DE COMUNICACIONES Y TRANSPORTES, MEDIANTE EL DECRETO DEL 7 DE DICIEMBRE DE 2020.',308134,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,400236,'DERECHO DE VISITANTE SIN PERMISO PARA REALIZAR ACTIVIDADES REMUNERADAS CON FINES TURÍSTICOS (DNR-T)',307182,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,400249,'DERECHO DE VISITANTE SIN PERMISO PARA REALIZAR ACTIVIDADES REMUNERADAS SIN FINES TURÍSTICOS (DNR-O)',307186,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,180003,'IMPUESTO POR LA ACTIVIDAD DE EXPLORACIÓN Y EXTRACCIÓN DE HIDROCARBUROS',0901,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,700193,'MULTAS PREVISTAS EN EL ART. 160 DE LA LEY NACIONAL DE EJECUCIÓN PENAL',506158,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,700194,'MULTAS IMPUESTAS POR LA OMISIÓN EN EL CUMPLIMIENTO DE LOS ARTÍCULOS 17 Y 18 DE LA LEY FEDERAL PARA LA PREVENCIÓN E IDENTIFICACIÓN DE OPERACIONES CON RECURSOS DE PROCEDENCIA ILÍCITA',50547,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,140042,'OTROS, GASOLINA (IMPORTACIÓN DE GASOLINA)',0442,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,140043,'PEMEX, DIÉSEL(IMPORTACIÓN DE DIÉSEL)',0443,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,140044,'OTROS, DIÉSEL (IMPORTACIÓN DE DIÉSEL)',0444,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,140045,'IMPORTACIÓN DE COMBUSTIBLES NO FÓSILES ',0445,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,500155,'IMPUESTO ESPECIAL SOBRE PRODUCCIÓN Y SERVICIOS (IMPUESTOS NO COMPRENDIDOS EN LA LEY DE INGRESOS VIGENTE, CAUSADOS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN)',0446,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,110081,'ISR RÉGIMEN SIMPLIFICADO DE CONFIANZA, PERSONAS FÍSICAS',0168,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,110083,'ISR RÉGIMEN SIMPLIFICADO DE CONFIANZA, PERSONAS MORALES',0167,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,130023,'IVA RÉGIMEN SIMPLIFICADO DE CONFIANZA',0318,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,400295,'SECRETARIA DE SALUD.',308126,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,400296,'SECRETARIA DE SEGURIDAD Y PROTECCION CIUDADANA.',308127,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,400297,'SECRETARIA DEL BIENESTAR.',308128,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,400298,'POR LA OBTENCION DE CODIGOS DE SEGURIDAD QUE SE IMPRIMAN EN LAS CAJETILLAS, ESTUCHES, EMPAQUES, ENVOLTURAS O CUALQUIER OTRO OBJETO QUE CONTENGA CIGARROS U OTROS TABACOS LABRADOS PARA VENTA EN MEXICO (ART.  53-I  DE LA LFD).',308129,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,400299,'POR LA OBTENCION DE FOLIOS ELECTRONICOS PARA LA IMPRESION DE MARBETES ELECTRONICOS QUE SE ADHIERAN A LOS ENVASES QUE CONTENGAN BEBIDAS ALCOHOLICAS A QUE SE REFIERE LA LEY DEL IMPUESTO ESPECIAL SOBRE PRODUCCION Y SERVICIOS (ART. 53-K, FRACCIÓN II DE LA LFD).',308130,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,500165,'DERECHOS DEROGADOS DE LA FISCALIA GENERAL DE LA REPUBLICA.',308131,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,500166,'DERECHO POR AUTORIZACION DE ARRIBO, DESPACHO, MANIOBRA DE FONDEO O ENMIENDA (ART. 170 DE LA LFD).',308132,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,500167,'POR EL DERECHO DE CUMPLIMIENTO DEL CODIGO INTERNACIONAL PARA LA PROTECCION DE LOS BUQUES Y DE LAS INSTALACIONES PORTUARIAS (ART. 170-G DE LA LFD).',308133,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(2,500168,'DERECHOS DEROGADOS DE LA SECRETARIA DE COMUNICACIONES Y TRANSPORTES, MEDIANTE EL DECRETO DEL 7 DE DICIEMBRE DE 2020.',308134,1);

INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,400236,'DERECHO DE VISITANTE SIN PERMISO PARA REALIZAR ACTIVIDADES REMUNERADAS CON FINES TURÍSTICOS (DNR-T)',307182,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,400249,'DERECHO DE VISITANTE SIN PERMISO PARA REALIZAR ACTIVIDADES REMUNERADAS SIN FINES TURÍSTICOS (DNR-O)',307186,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,180003,'IMPUESTO POR LA ACTIVIDAD DE EXPLORACIÓN Y EXTRACCIÓN DE HIDROCARBUROS',0901,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,700193,'MULTAS PREVISTAS EN EL ART. 160 DE LA LEY NACIONAL DE EJECUCIÓN PENAL',506158,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,700194,'MULTAS IMPUESTAS POR LA OMISIÓN EN EL CUMPLIMIENTO DE LOS ARTÍCULOS 17 Y 18 DE LA LEY FEDERAL PARA LA PREVENCIÓN E IDENTIFICACIÓN DE OPERACIONES CON RECURSOS DE PROCEDENCIA ILÍCITA',50547,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,140042,'OTROS, GASOLINA (IMPORTACIÓN DE GASOLINA)',0442,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,140043,'PEMEX, DIÉSEL(IMPORTACIÓN DE DIÉSEL)',0443,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,140044,'OTROS, DIÉSEL (IMPORTACIÓN DE DIÉSEL)',0444,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,140045,'IMPORTACIÓN DE COMBUSTIBLES NO FÓSILES ',0445,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,500155,'IMPUESTO ESPECIAL SOBRE PRODUCCIÓN Y SERVICIOS (IMPUESTOS NO COMPRENDIDOS EN LA LEY DE INGRESOS VIGENTE, CAUSADOS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN)',0446,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,110081,'ISR RÉGIMEN SIMPLIFICADO DE CONFIANZA, PERSONAS FÍSICAS',0168,1)
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,110083,'ISR RÉGIMEN SIMPLIFICADO DE CONFIANZA, PERSONAS MORALES',0167,1)
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,130023,'IVA RÉGIMEN SIMPLIFICADO DE CONFIANZA',0318,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,400295,'SECRETARIA DE SALUD.',308126,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,400296,'SECRETARIA DE SEGURIDAD Y PROTECCION CIUDADANA.',308127,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,400297,'SECRETARIA DEL BIENESTAR.',308128,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,400298,'POR LA OBTENCION DE CODIGOS DE SEGURIDAD QUE SE IMPRIMAN EN LAS CAJETILLAS, ESTUCHES, EMPAQUES, ENVOLTURAS O CUALQUIER OTRO OBJETO QUE CONTENGA CIGARROS U OTROS TABACOS LABRADOS PARA VENTA EN MEXICO (ART.  53-I  DE LA LFD).',308129,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,400299,'POR LA OBTENCION DE FOLIOS ELECTRONICOS PARA LA IMPRESION DE MARBETES ELECTRONICOS QUE SE ADHIERAN A LOS ENVASES QUE CONTENGAN BEBIDAS ALCOHOLICAS A QUE SE REFIERE LA LEY DEL IMPUESTO ESPECIAL SOBRE PRODUCCION Y SERVICIOS (ART. 53-K, FRACCIÓN II DE LA LFD).',308130,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,500165,'DERECHOS DEROGADOS DE LA FISCALIA GENERAL DE LA REPUBLICA.',308131,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,500166,'DERECHO POR AUTORIZACION DE ARRIBO, DESPACHO, MANIOBRA DE FONDEO O ENMIENDA (ART. 170 DE LA LFD).',308132,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,500167,'POR EL DERECHO DE CUMPLIMIENTO DEL CODIGO INTERNACIONAL PARA LA PROTECCION DE LOS BUQUES Y DE LAS INSTALACIONES PORTUARIAS (ART. 170-G DE LA LFD).',308133,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(4,500168,'DERECHOS DEROGADOS DE LA SECRETARIA DE COMUNICACIONES Y TRANSPORTES, MEDIANTE EL DECRETO DEL 7 DE DICIEMBRE DE 2020.',308134,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,400236,'DERECHO DE VISITANTE SIN PERMISO PARA REALIZAR ACTIVIDADES REMUNERADAS CON FINES TURÍSTICOS (DNR-T)',307182,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,400249,'DERECHO DE VISITANTE SIN PERMISO PARA REALIZAR ACTIVIDADES REMUNERADAS SIN FINES TURÍSTICOS (DNR-O)',307186,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,180003,'IMPUESTO POR LA ACTIVIDAD DE EXPLORACIÓN Y EXTRACCIÓN DE HIDROCARBUROS',0901,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,700193,'MULTAS PREVISTAS EN EL ART. 160 DE LA LEY NACIONAL DE EJECUCIÓN PENAL',506158,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,700194,'MULTAS IMPUESTAS POR LA OMISIÓN EN EL CUMPLIMIENTO DE LOS ARTÍCULOS 17 Y 18 DE LA LEY FEDERAL PARA LA PREVENCIÓN E IDENTIFICACIÓN DE OPERACIONES CON RECURSOS DE PROCEDENCIA ILÍCITA',50547,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,140042,'OTROS, GASOLINA (IMPORTACIÓN DE GASOLINA)',0442,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,140043,'PEMEX, DIÉSEL(IMPORTACIÓN DE DIÉSEL)',0443,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,140044,'OTROS, DIÉSEL (IMPORTACIÓN DE DIÉSEL)',0444,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,140045,'IMPORTACIÓN DE COMBUSTIBLES NO FÓSILES ',0445,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,500155,'IMPUESTO ESPECIAL SOBRE PRODUCCIÓN Y SERVICIOS (IMPUESTOS NO COMPRENDIDOS EN LA LEY DE INGRESOS VIGENTE, CAUSADOS EN EJERCICIOS FISCALES ANTERIORES PENDIENTES DE LIQUIDACIÓN)',0446,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,110081,'ISR RÉGIMEN SIMPLIFICADO DE CONFIANZA, PERSONAS FÍSICAS',0168,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,110083,'ISR RÉGIMEN SIMPLIFICADO DE CONFIANZA, PERSONAS MORALES',0167,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,130023,'IVA RÉGIMEN SIMPLIFICADO DE CONFIANZA',0318,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,400295,'SECRETARIA DE SALUD.',308126,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,400296,'SECRETARIA DE SEGURIDAD Y PROTECCION CIUDADANA.',308127,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,400297,'SECRETARIA DEL BIENESTAR.',308128,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,400298,'POR LA OBTENCION DE CODIGOS DE SEGURIDAD QUE SE IMPRIMAN EN LAS CAJETILLAS, ESTUCHES, EMPAQUES, ENVOLTURAS O CUALQUIER OTRO OBJETO QUE CONTENGA CIGARROS U OTROS TABACOS LABRADOS PARA VENTA EN MEXICO (ART.  53-I  DE LA LFD).',308129,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,400299,'POR LA OBTENCION DE FOLIOS ELECTRONICOS PARA LA IMPRESION DE MARBETES ELECTRONICOS QUE SE ADHIERAN A LOS ENVASES QUE CONTENGAN BEBIDAS ALCOHOLICAS A QUE SE REFIERE LA LEY DEL IMPUESTO ESPECIAL SOBRE PRODUCCION Y SERVICIOS (ART. 53-K, FRACCIÓN II DE LA LFD).',308130,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,500165,'DERECHOS DEROGADOS DE LA FISCALIA GENERAL DE LA REPUBLICA.',308131,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,500166,'DERECHO POR AUTORIZACION DE ARRIBO, DESPACHO, MANIOBRA DE FONDEO O ENMIENDA (ART. 170 DE LA LFD).',308132,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,500167,'POR EL DERECHO DE CUMPLIMIENTO DEL CODIGO INTERNACIONAL PARA LA PROTECCION DE LOS BUQUES Y DE LAS INSTALACIONES PORTUARIAS (ART. 170-G DE LA LFD).',308133,1);
INSERT INTO [MotorTraductor].[dbo].[CatConceptoEquivalencia] ([IdAplicacion],[ConceptoOrigen],[DescripcionOrigen],[ConceptoDyP],[Activo]) VALUES(5,500168,'DERECHOS DEROGADOS DE LA SECRETARIA DE COMUNICACIONES Y TRANSPORTES, MEDIANTE EL DECRETO DEL 7 DE DICIEMBRE DE 2020.',308134,1);
COMMIT TRAN
go

SELECT * FROM [MotorTraductor].[dbo].[CatConceptoDyP] 
GO

SELECT * FROM [MotorTraductor].[dbo].[CatConceptoEquivalencia]
GO